/// Thin C++ shim that bridges the Rust vulkan-compute C API
/// into PyTorch's PrivateUse1 dispatch registration.

#include <torch/extension.h>
#include <c10/core/Allocator.h>
#include <c10/core/impl/DeviceGuardImplInterface.h>
#include <ATen/detail/PrivateUse1HooksInterface.h>
#include <ATen/native/CPUFallback.h>
#include <ATen/InferSize.h>

#include <cstring>
#include <stdexcept>
#include <string>
#include <tuple>
#include <vector>
#include <unordered_map>

// C API from Rust (generated by cbindgen).
extern "C" {
  int32_t vkc_init();
  int32_t vkc_is_available();
  int32_t vkc_device_name(char* buf, size_t buf_len);
  uint8_t* vkc_alloc(size_t size, void** out_handle);
  void vkc_free(void* handle);
  int32_t vkc_flush();
  int32_t vkc_fill_buffer(const uint8_t* mapped_ptr, size_t size, uint32_t value);
  int32_t vkc_copy_buffer(const uint8_t* src_mapped_ptr, const uint8_t* dst_mapped_ptr, size_t size);
  void* vkc_load_shader(const uint8_t* spirv_data, size_t spirv_len);
  int32_t vkc_dispatch(
      void* pipeline_handle,
      const uint8_t** buffers,
      size_t num_buffers,
      uint32_t group_count_x,
      uint32_t group_count_y,
      uint32_t group_count_z,
      const uint8_t* push_constants,
      size_t push_constants_len);
  void* vkc_get_buffer_for_ptr(const uint8_t* mapped_ptr);
  int32_t vkc_has_buffer(const uint8_t* mapped_ptr);
}

namespace {

// ---------------------------------------------------------------------------
// Allocator: routes PyTorch storage allocations to Rust vkc_alloc/vkc_free
// ---------------------------------------------------------------------------

struct RustVulkanAllocator final : public c10::Allocator {
  c10::DataPtr allocate(size_t n) override {
    if (n == 0) {
      return {nullptr, nullptr, &raw_delete, c10::Device(c10::DeviceType::PrivateUse1, 0)};
    }
    void* handle = nullptr;
    uint8_t* ptr = vkc_alloc(n, &handle);
    if (!ptr) {
      throw std::runtime_error("Vulkan allocation failed for " + std::to_string(n) + " bytes");
    }
    return {ptr, handle, &raw_delete, c10::Device(c10::DeviceType::PrivateUse1, 0)};
  }

  c10::DeleterFnPtr raw_deleter() const override {
    return &raw_delete;
  }

  void copy_data(void* dest, const void* src, std::size_t count) const override {
    std::memcpy(dest, src, count);
  }

  static void raw_delete(void* ctx) {
    if (ctx) {
      vkc_free(ctx);
    }
  }
};

static RustVulkanAllocator g_allocator;

// ---------------------------------------------------------------------------
// DeviceGuard: single-device stub
// ---------------------------------------------------------------------------

struct VulkanGuardImpl final : public c10::impl::DeviceGuardImplInterface {
  c10::DeviceType type() const override {
    return c10::DeviceType::PrivateUse1;
  }
  c10::Device exchangeDevice(c10::Device) const override {
    return c10::Device(c10::DeviceType::PrivateUse1, 0);
  }
  c10::Device getDevice() const override {
    return c10::Device(c10::DeviceType::PrivateUse1, 0);
  }
  void setDevice(c10::Device) const override {}
  void uncheckedSetDevice(c10::Device) const noexcept override {}
  c10::Stream getStream(c10::Device) const noexcept override {
    return c10::Stream(c10::Stream::DEFAULT, c10::Device(c10::DeviceType::PrivateUse1, 0));
  }
  c10::Stream getDefaultStream(c10::Device) const override {
    return c10::Stream(c10::Stream::DEFAULT, c10::Device(c10::DeviceType::PrivateUse1, 0));
  }
  c10::Stream exchangeStream(c10::Stream) const noexcept override {
    return c10::Stream(c10::Stream::DEFAULT, c10::Device(c10::DeviceType::PrivateUse1, 0));
  }
  c10::DeviceIndex deviceCount() const noexcept override {
    return 1;
  }
};

static auto g_guard_reg = c10::impl::DeviceGuardImplRegistrar(
    c10::DeviceType::PrivateUse1,
    new VulkanGuardImpl());

static std::unordered_map<std::string, int64_t> g_shader_handles;

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

static bool is_vulkan(const at::Tensor& t) {
  return t.device().type() == c10::DeviceType::PrivateUse1;
}

// Check if a tensor's storage is actually backed by our Vulkan allocator.
// A tensor can be PrivateUse1 but not have a registered buffer if it was
// created by internal PyTorch ops (e.g. isfinite, autograd intermediates).
static bool has_vulkan_buffer(const at::Tensor& t) {
  if (!is_vulkan(t) || t.numel() == 0) return false;
  const uint8_t* base_ptr = reinterpret_cast<const uint8_t*>(t.storage().data_ptr().get());
  return vkc_has_buffer(base_ptr) == 1;
}

// Ensure both tensors are on Vulkan with registered buffers.
static bool both_vulkan(const at::Tensor& a, const at::Tensor& b) {
  return has_vulkan_buffer(a) && has_vulkan_buffer(b);
}

// ---------------------------------------------------------------------------
// Native Compute Ops
// ---------------------------------------------------------------------------

// Expand operands to a common broadcast shape and make them contiguous.
// Returns false if broadcasting is not needed (shapes already match).
static bool needs_broadcast(const at::Tensor& a, const at::Tensor& b) {
  return a.sizes() != b.sizes();
}

static std::pair<at::Tensor, at::Tensor> broadcast_operands(
    const at::Tensor& a, const at::Tensor& b) {
  auto shape = at::infer_size(a.sizes(), b.sizes());
  return {a.expand(shape).contiguous(), b.expand(shape).contiguous()};
}

// Select the right shader for dtype (f32 or f16 variant).
static std::unordered_map<std::string, int64_t>::iterator
find_shader_for_dtype(const std::string& base_name, c10::ScalarType dtype) {
  if (dtype == c10::ScalarType::Half) {
    auto it = g_shader_handles.find(base_name + "_f16");
    if (it != g_shader_handles.end()) return it;
  } else if (dtype == c10::ScalarType::BFloat16) {
    auto it = g_shader_handles.find(base_name + "_bf16");
    if (it != g_shader_handles.end()) return it;
  }
  return g_shader_handles.find(base_name);
}

at::Tensor add_vulkan(const at::Tensor& self, const at::Tensor& other, const at::Scalar& alpha) {
  auto it = find_shader_for_dtype("add", self.scalar_type());
  if (it == g_shader_handles.end() || alpha.toFloat() != 1.0f || !both_vulkan(self, other)) {
    vkc_flush();
    return at::add(self.cpu(), other.cpu(), alpha).to(self.options());
  }

  auto [a, b] = needs_broadcast(self, other)
      ? broadcast_operands(self, other)
      : std::make_pair(self.contiguous(), other.contiguous());
  auto out = at::empty_like(a);
  uint32_t num_elements = a.numel();
  uint32_t groups_x = (num_elements + 255) / 256;

  std::vector<const uint8_t*> ptrs = {
      reinterpret_cast<const uint8_t*>(a.data_ptr()),
      reinterpret_cast<const uint8_t*>(b.data_ptr()),
      reinterpret_cast<const uint8_t*>(out.data_ptr())};

  std::string pc_data;
  pc_data.resize(sizeof(uint32_t));
  std::memcpy(pc_data.data(), &num_elements, sizeof(uint32_t));

  int32_t result = vkc_dispatch(
      reinterpret_cast<void*>(it->second),
      ptrs.data(), ptrs.size(),
      groups_x, 1, 1,
      reinterpret_cast<const uint8_t*>(pc_data.data()), pc_data.size());

  TORCH_CHECK(result == 0, "add_vulkan dispatch failed");
  return out;
}

at::Tensor& add__vulkan(at::Tensor& self, const at::Tensor& other, const at::Scalar& alpha) {
  auto it = find_shader_for_dtype("add", self.scalar_type());
  if (it == g_shader_handles.end() || alpha.toFloat() != 1.0f || !both_vulkan(self, other) || !self.is_contiguous()) {
    vkc_flush();
    auto self_cpu = at::from_blob(self.data_ptr(), self.sizes(), self.strides(), at::TensorOptions().dtype(self.scalar_type()).device(c10::kCPU));
    self_cpu.add_(other.cpu(), alpha);
    return self;
  }

  auto b = other.expand(self.sizes()).contiguous();
  uint32_t num_elements = self.numel();
  uint32_t groups_x = (num_elements + 255) / 256;

  std::vector<const uint8_t*> ptrs = {
      reinterpret_cast<const uint8_t*>(self.data_ptr()),
      reinterpret_cast<const uint8_t*>(b.data_ptr()),
      reinterpret_cast<const uint8_t*>(self.data_ptr())};

  std::string pc_data;
  pc_data.resize(sizeof(uint32_t));
  std::memcpy(pc_data.data(), &num_elements, sizeof(uint32_t));

  int32_t result = vkc_dispatch(
      reinterpret_cast<void*>(it->second),
      ptrs.data(), ptrs.size(),
      groups_x, 1, 1,
      reinterpret_cast<const uint8_t*>(pc_data.data()), pc_data.size());

  TORCH_CHECK(result == 0, "add__vulkan dispatch failed");
  return self;
}

at::Tensor& add_out_vulkan(const at::Tensor& self, const at::Tensor& other, const at::Scalar& alpha, at::Tensor& out) {
  auto it = find_shader_for_dtype("add", self.scalar_type());
  if (it == g_shader_handles.end() || alpha.toFloat() != 1.0f || !both_vulkan(self, other) || !has_vulkan_buffer(out) || !out.is_contiguous()) {
    vkc_flush();
    auto self_cpu = at::from_blob(const_cast<void*>(self.data_ptr()), self.sizes(), self.strides(), at::TensorOptions().dtype(self.scalar_type()).device(c10::kCPU));
    auto other_cpu = at::from_blob(const_cast<void*>(other.data_ptr()), other.sizes(), other.strides(), at::TensorOptions().dtype(other.scalar_type()).device(c10::kCPU));
    auto out_cpu = at::from_blob(out.data_ptr(), out.sizes(), out.strides(), at::TensorOptions().dtype(out.scalar_type()).device(c10::kCPU));
    at::add_out(out_cpu, self_cpu, other_cpu, alpha);
    return out;
  }

  auto [a, b] = needs_broadcast(self, other)
      ? broadcast_operands(self, other)
      : std::make_pair(self.contiguous(), other.contiguous());

  uint32_t num_elements = a.numel();
  uint32_t groups_x = (num_elements + 255) / 256;

  std::vector<const uint8_t*> ptrs = {
      reinterpret_cast<const uint8_t*>(a.data_ptr()),
      reinterpret_cast<const uint8_t*>(b.data_ptr()),
      reinterpret_cast<const uint8_t*>(out.data_ptr())};

  std::string pc_data;
  pc_data.resize(sizeof(uint32_t));
  std::memcpy(pc_data.data(), &num_elements, sizeof(uint32_t));

  int32_t result = vkc_dispatch(
      reinterpret_cast<void*>(it->second),
      ptrs.data(), ptrs.size(),
      groups_x, 1, 1,
      reinterpret_cast<const uint8_t*>(pc_data.data()), pc_data.size());

  TORCH_CHECK(result == 0, "add_out_vulkan dispatch failed");
  return out;
}

at::Tensor mul_vulkan(const at::Tensor& self, const at::Tensor& other) {
  auto it = find_shader_for_dtype("mul", self.scalar_type());
  if (it == g_shader_handles.end() || !both_vulkan(self, other)) {
    vkc_flush();
    return at::mul(self.cpu(), other.cpu()).to(self.options());
  }

  auto [a, b] = needs_broadcast(self, other)
      ? broadcast_operands(self, other)
      : std::make_pair(self.contiguous(), other.contiguous());
  auto out = at::empty_like(a);
  uint32_t num_elements = a.numel();
  uint32_t groups_x = (num_elements + 255) / 256;

  std::vector<const uint8_t*> ptrs = {
      reinterpret_cast<const uint8_t*>(a.data_ptr()),
      reinterpret_cast<const uint8_t*>(b.data_ptr()),
      reinterpret_cast<const uint8_t*>(out.data_ptr())};

  std::string pc_data;
  pc_data.resize(sizeof(uint32_t));
  std::memcpy(pc_data.data(), &num_elements, sizeof(uint32_t));

  int32_t result = vkc_dispatch(
      reinterpret_cast<void*>(it->second),
      ptrs.data(), ptrs.size(),
      groups_x, 1, 1,
      reinterpret_cast<const uint8_t*>(pc_data.data()), pc_data.size());

  TORCH_CHECK(result == 0, "mul_vulkan dispatch failed");
  return out;
}

at::Tensor sub_vulkan(const at::Tensor& self, const at::Tensor& other, const at::Scalar& alpha) {
  auto it = find_shader_for_dtype("sub", self.scalar_type());
  if (it == g_shader_handles.end() || alpha.toFloat() != 1.0f || !both_vulkan(self, other)) {
    vkc_flush();
    return at::sub(self.cpu(), other.cpu(), alpha).to(self.options());
  }

  auto [a, b] = needs_broadcast(self, other)
      ? broadcast_operands(self, other)
      : std::make_pair(self.contiguous(), other.contiguous());
  auto out = at::empty_like(a);
  uint32_t num_elements = a.numel();
  uint32_t groups_x = (num_elements + 255) / 256;

  std::vector<const uint8_t*> ptrs = {
      reinterpret_cast<const uint8_t*>(a.data_ptr()),
      reinterpret_cast<const uint8_t*>(b.data_ptr()),
      reinterpret_cast<const uint8_t*>(out.data_ptr())};

  std::string pc_data;
  pc_data.resize(sizeof(uint32_t));
  std::memcpy(pc_data.data(), &num_elements, sizeof(uint32_t));

  int32_t result = vkc_dispatch(
      reinterpret_cast<void*>(it->second),
      ptrs.data(), ptrs.size(),
      groups_x, 1, 1,
      reinterpret_cast<const uint8_t*>(pc_data.data()), pc_data.size());

  TORCH_CHECK(result == 0, "sub_vulkan dispatch failed");
  return out;
}


at::Tensor& sub_out_vulkan(const at::Tensor& self, const at::Tensor& other, const at::Scalar& alpha, at::Tensor& out) {
  auto it = find_shader_for_dtype("sub", self.scalar_type());
  if (it == g_shader_handles.end() || alpha.toFloat() != 1.0f || !both_vulkan(self, other) || !has_vulkan_buffer(out) || !out.is_contiguous()) {
    vkc_flush();
    auto self_cpu = at::from_blob(const_cast<void*>(self.data_ptr()), self.sizes(), self.strides(), at::TensorOptions().dtype(self.scalar_type()).device(c10::kCPU));
    auto other_cpu = at::from_blob(const_cast<void*>(other.data_ptr()), other.sizes(), other.strides(), at::TensorOptions().dtype(other.scalar_type()).device(c10::kCPU));
    auto out_cpu = at::from_blob(out.data_ptr(), out.sizes(), out.strides(), at::TensorOptions().dtype(out.scalar_type()).device(c10::kCPU));
    at::sub_out(out_cpu, self_cpu, other_cpu, alpha);
    return out;
  }

  auto [a, b] = needs_broadcast(self, other)
      ? broadcast_operands(self, other)
      : std::make_pair(self.contiguous(), other.contiguous());

  uint32_t num_elements = a.numel();
  uint32_t groups_x = (num_elements + 255) / 256;

  std::vector<const uint8_t*> ptrs = {
      reinterpret_cast<const uint8_t*>(a.data_ptr()),
      reinterpret_cast<const uint8_t*>(b.data_ptr()),
      reinterpret_cast<const uint8_t*>(out.data_ptr())};

  std::string pc_data;
  pc_data.resize(sizeof(uint32_t));
  std::memcpy(pc_data.data(), &num_elements, sizeof(uint32_t));

  int32_t result = vkc_dispatch(
      reinterpret_cast<void*>(it->second),
      ptrs.data(), ptrs.size(),
      groups_x, 1, 1,
      reinterpret_cast<const uint8_t*>(pc_data.data()), pc_data.size());

  TORCH_CHECK(result == 0, "sub_out_vulkan dispatch failed");
  return out;
}



at::Tensor div_vulkan(const at::Tensor& self, const at::Tensor& other) {
  auto it = find_shader_for_dtype("div", self.scalar_type());
  if (it == g_shader_handles.end() || !both_vulkan(self, other)) {
    vkc_flush();
    return at::div(self.cpu(), other.cpu()).to(self.options());
  }

  auto [a, b] = needs_broadcast(self, other)
      ? broadcast_operands(self, other)
      : std::make_pair(self.contiguous(), other.contiguous());
  auto out = at::empty_like(a);
  uint32_t num_elements = a.numel();
  uint32_t groups_x = (num_elements + 255) / 256;

  std::vector<const uint8_t*> ptrs = {
      reinterpret_cast<const uint8_t*>(a.data_ptr()),
      reinterpret_cast<const uint8_t*>(b.data_ptr()),
      reinterpret_cast<const uint8_t*>(out.data_ptr())};

  std::string pc_data;
  pc_data.resize(sizeof(uint32_t));
  std::memcpy(pc_data.data(), &num_elements, sizeof(uint32_t));

  int32_t result = vkc_dispatch(
      reinterpret_cast<void*>(it->second),
      ptrs.data(), ptrs.size(),
      groups_x, 1, 1,
      reinterpret_cast<const uint8_t*>(pc_data.data()), pc_data.size());

  TORCH_CHECK(result == 0, "div_vulkan dispatch failed");
  return out;
}

at::Tensor threshold_backward_vulkan(
    const at::Tensor& grad_output, const at::Tensor& self, const at::Scalar& threshold) {
  auto it = g_shader_handles.find("threshold_backward");
  if (it == g_shader_handles.end() || !has_vulkan_buffer(grad_output) || !has_vulkan_buffer(self)) {
    vkc_flush();
    return at::threshold_backward(grad_output.cpu(), self.cpu(), threshold).to(grad_output.options());
  }

  auto go = grad_output.contiguous();
  auto inp = self.contiguous();
  auto out = at::empty_like(go);
  uint32_t num_elements = go.numel();
  uint32_t groups_x = (num_elements + 255) / 256;

  // Push constants: num_elements + threshold (as float)
  struct { uint32_t n; float t; } pc = {num_elements, threshold.toFloat()};

  std::vector<const uint8_t*> ptrs = {
      reinterpret_cast<const uint8_t*>(go.data_ptr()),
      reinterpret_cast<const uint8_t*>(inp.data_ptr()),
      reinterpret_cast<const uint8_t*>(out.data_ptr())};

  int32_t result = vkc_dispatch(
      reinterpret_cast<void*>(it->second),
      ptrs.data(), ptrs.size(),
      groups_x, 1, 1,
      reinterpret_cast<const uint8_t*>(&pc), sizeof(pc));

  TORCH_CHECK(result == 0, "threshold_backward_vulkan dispatch failed");
  return out;
}

at::Tensor cat_vulkan(const at::ITensorListRef& tensors, int64_t dim) {
  auto tensor_list = tensors.materialize();

  // Fast path: exactly 2 contiguous same-dtype tensors with registered buffers.
  if (tensor_list.size() == 2) {
    auto& a = tensor_list[0].get();
    auto& b = tensor_list[1].get();

    if (has_vulkan_buffer(a) && has_vulkan_buffer(b) &&
        a.dtype() == b.dtype() && a.is_contiguous() && b.is_contiguous()) {

      int64_t ndim = a.dim();
      if (dim < 0) dim += ndim;

      // Check all dims match except the cat dim.
      bool shapes_ok = (a.dim() == b.dim());
      for (int64_t i = 0; i < ndim && shapes_ok; i++) {
        if (i != dim) shapes_ok = (a.size(i) == b.size(i));
      }

      if (shapes_ok) {
        auto it = find_shader_for_dtype("cat2", a.scalar_type());
        if (it != g_shader_handles.end()) {
          // Compute inner sizes (product of dims after cat dim).
          int64_t inner_a = a.size(dim);
          int64_t inner_b = b.size(dim);
          for (int64_t i = dim + 1; i < ndim; i++) {
            inner_a *= a.size(i);
            inner_b *= b.size(i);
          }

          // Build output shape.
          std::vector<int64_t> out_sizes;
          for (int64_t i = 0; i < ndim; i++) {
            out_sizes.push_back(i == dim ? a.size(i) + b.size(i) : a.size(i));
          }
          auto out = at::empty(out_sizes, a.options());
          uint32_t num_elements = out.numel();
          uint32_t groups_x = (num_elements + 255) / 256;

          struct { uint32_t n, ia, ib; } pc = {
              num_elements,
              static_cast<uint32_t>(inner_a),
              static_cast<uint32_t>(inner_b)};

          std::vector<const uint8_t*> ptrs = {
              reinterpret_cast<const uint8_t*>(a.data_ptr()),
              reinterpret_cast<const uint8_t*>(b.data_ptr()),
              reinterpret_cast<const uint8_t*>(out.data_ptr())};

          int32_t result = vkc_dispatch(
              reinterpret_cast<void*>(it->second),
              ptrs.data(), ptrs.size(),
              groups_x, 1, 1,
              reinterpret_cast<const uint8_t*>(&pc), sizeof(pc));

          if (result == 0) return out;
        }
      }
    }
  }

  // Fallback: CPU cat.
  vkc_flush();
  std::vector<at::Tensor> cpu_tensors;
  for (auto& t : tensor_list) {
    cpu_tensors.push_back(t.get().cpu());
  }
  auto result = at::cat(cpu_tensors, dim);
  return result.to(tensor_list[0].get().options());
}

#define DEFINE_UNARY_OP(op_name, shader_key) \
  at::Tensor op_name##_vulkan(const at::Tensor& self) { \
    auto it = find_shader_for_dtype(shader_key, self.scalar_type()); \
    if (it == g_shader_handles.end() || !has_vulkan_buffer(self)) { \
      vkc_flush(); \
      return at::op_name(self.cpu()).to(self.options()); \
    } \
    auto out = at::empty_like(self); \
    uint32_t num_elements = self.numel(); \
    uint32_t groups_x = (num_elements + 255) / 256; \
    std::vector<const uint8_t*> ptrs = { \
        reinterpret_cast<const uint8_t*>(self.data_ptr()), \
        reinterpret_cast<const uint8_t*>(out.data_ptr())}; \
    std::string pc_data; \
    pc_data.resize(sizeof(uint32_t)); \
    std::memcpy(pc_data.data(), &num_elements, sizeof(uint32_t)); \
    int32_t result = vkc_dispatch( \
        reinterpret_cast<void*>(it->second), \
        ptrs.data(), ptrs.size(), \
        groups_x, 1, 1, \
        reinterpret_cast<const uint8_t*>(pc_data.data()), pc_data.size()); \
    TORCH_CHECK(result == 0, #op_name "_vulkan dispatch failed"); \
    return out; \
  }

DEFINE_UNARY_OP(relu, "relu");
DEFINE_UNARY_OP(neg, "neg");
DEFINE_UNARY_OP(sigmoid, "sigmoid");
DEFINE_UNARY_OP(tanh, "tanh");
DEFINE_UNARY_OP(exp, "exp");
DEFINE_UNARY_OP(log, "log");
DEFINE_UNARY_OP(silu, "silu");
DEFINE_UNARY_OP(sqrt, "sqrt");
DEFINE_UNARY_OP(rsqrt, "rsqrt");
DEFINE_UNARY_OP(abs, "abs");

at::Tensor pow_tensor_scalar_vulkan(const at::Tensor& self, const at::Scalar& exponent) {
  auto it = g_shader_handles.find("pow");
  if (it == g_shader_handles.end() || !has_vulkan_buffer(self)) {
    vkc_flush();
    return at::pow(self.cpu(), exponent).to(self.options());
  }

  auto input = self.contiguous();
  auto out = at::empty_like(input);
  uint32_t num_elements = input.numel();
  uint32_t groups_x = (num_elements + 255) / 256;

  struct { uint32_t n; float exp; } pc = {num_elements, exponent.toFloat()};

  std::vector<const uint8_t*> ptrs = {
      reinterpret_cast<const uint8_t*>(input.data_ptr()),
      reinterpret_cast<const uint8_t*>(out.data_ptr())};

  int32_t result = vkc_dispatch(
      reinterpret_cast<void*>(it->second),
      ptrs.data(), ptrs.size(),
      groups_x, 1, 1,
      reinterpret_cast<const uint8_t*>(&pc), sizeof(pc));

  TORCH_CHECK(result == 0, "pow_vulkan dispatch failed");
  return out;
}

at::Tensor gelu_vulkan(const at::Tensor& self, std::string_view approximate) {
  auto it = g_shader_handles.find("gelu");
  if (it == g_shader_handles.end()) {
    vkc_flush();
    return at::gelu(self.cpu(), approximate).to(self.options());
  }
  auto out = at::empty_like(self);
  uint32_t num_elements = self.numel();
  uint32_t groups_x = (num_elements + 255) / 256;
  std::vector<const uint8_t*> ptrs = {
      reinterpret_cast<const uint8_t*>(self.data_ptr()),
      reinterpret_cast<const uint8_t*>(out.data_ptr())};
  std::string pc_data;
  pc_data.resize(sizeof(uint32_t));
  std::memcpy(pc_data.data(), &num_elements, sizeof(uint32_t));
  int32_t result = vkc_dispatch(
      reinterpret_cast<void*>(it->second),
      ptrs.data(), ptrs.size(),
      groups_x, 1, 1,
      reinterpret_cast<const uint8_t*>(pc_data.data()), pc_data.size());
  TORCH_CHECK(result == 0, "gelu_vulkan dispatch failed");
  return out;
}

#pragma pack(push, 1)
struct LayerNormPushConstants {
    uint32_t outer_size;
    uint32_t dim_size;
    float eps;
    uint32_t has_weight_bias;
};
#pragma pack(pop)

std::tuple<at::Tensor, at::Tensor, at::Tensor> native_layer_norm_vulkan(
    const at::Tensor& input,
    c10::IntArrayRef normalized_shape,
    const std::optional<at::Tensor>& weight_opt,
    const std::optional<at::Tensor>& bias_opt,
    double eps) {

  auto it = g_shader_handles.find("layer_norm");
  if (it == g_shader_handles.end()) {
    vkc_flush();
    auto w = weight_opt.has_value() ? std::make_optional(weight_opt.value().cpu()) : std::nullopt;
    auto b = bias_opt.has_value() ? std::make_optional(bias_opt.value().cpu()) : std::nullopt;
    auto res = at::native_layer_norm(input.cpu(), normalized_shape, w, b, eps);
    return std::make_tuple(
        std::get<0>(res).to(input.options()),
        std::get<1>(res).to(input.options()),
        std::get<2>(res).to(input.options()));
  }

  at::Tensor work = input;
  if (!work.is_contiguous() || work.storage_offset() > 0) {
      work = work.clone(at::MemoryFormat::Contiguous);
  }

  int64_t dim_size = 1;
  for (auto s : normalized_shape) {
      dim_size *= s;
  }
  int64_t outer_size = work.numel() / dim_size;

  std::vector<int64_t> stat_shape;
  for (int64_t i = 0; i < work.dim() - normalized_shape.size(); i++) stat_shape.push_back(work.size(i));
  for (size_t i = 0; i < normalized_shape.size(); i++) stat_shape.push_back(1);

  auto out = at::empty_like(work);
  auto mean = at::empty(stat_shape, work.options());
  auto rstd = at::empty(stat_shape, work.options());

  std::vector<const uint8_t*> ptrs = {
      reinterpret_cast<const uint8_t*>(work.data_ptr())
  };

  uint32_t has_wb = 0;
  at::Tensor dummy_w = at::empty({0}, input.options());
  at::Tensor dummy_b = at::empty({0}, input.options());

  if (weight_opt.has_value() && bias_opt.has_value()) {
      has_wb = 1;
      ptrs.push_back(reinterpret_cast<const uint8_t*>(weight_opt.value().data_ptr()));
      ptrs.push_back(reinterpret_cast<const uint8_t*>(bias_opt.value().data_ptr()));
  } else {
      ptrs.push_back(reinterpret_cast<const uint8_t*>(dummy_w.data_ptr()));
      ptrs.push_back(reinterpret_cast<const uint8_t*>(dummy_b.data_ptr()));
  }
  ptrs.push_back(reinterpret_cast<const uint8_t*>(out.data_ptr()));

  LayerNormPushConstants pc = {
      static_cast<uint32_t>(outer_size),
      static_cast<uint32_t>(dim_size),
      static_cast<float>(eps),
      has_wb
  };

  int32_t result = vkc_dispatch(
      reinterpret_cast<void*>(it->second),
      ptrs.data(), ptrs.size(),
      outer_size, 1, 1,
      reinterpret_cast<const uint8_t*>(&pc), sizeof(pc));

  TORCH_CHECK(result == 0, "layer_norm_vulkan dispatch failed");

  return std::make_tuple(out, mean, rstd);
}

#pragma pack(push, 1)
struct RMSNormPushConstants {
    uint32_t outer_size;
    uint32_t dim_size;
    float eps;
    uint32_t has_weight;
};
#pragma pack(pop)

std::tuple<at::Tensor, at::Tensor> native_rmsnorm_vulkan(
    const at::Tensor& input,
    c10::IntArrayRef normalized_shape,
    const std::optional<at::Tensor>& weight_opt,
    double eps) {

  auto it = find_shader_for_dtype("rmsnorm", input.scalar_type());
  if (it == g_shader_handles.end()) {
    vkc_flush();
    // Manual RMS norm fallback on CPU.
    auto x = input.cpu().to(at::kFloat);
    auto rms = x.pow(2).mean(-1, true).add(eps).sqrt();
    auto normed = x / rms;
    if (weight_opt.has_value()) normed = normed * weight_opt.value().cpu();
    auto rstd_cpu = rms.reciprocal();
    return std::make_tuple(
        normed.to(input.options()),
        rstd_cpu.to(input.options()));
  }

  at::Tensor work = input;
  if (!work.is_contiguous() || work.storage_offset() > 0) {
      work = work.clone(at::MemoryFormat::Contiguous);
  }
  int64_t dim_size = 1;
  for (auto s : normalized_shape) {
      dim_size *= s;
  }
  int64_t outer_size = work.numel() / dim_size;

  std::vector<int64_t> stat_shape;
  for (int64_t i = 0; i < work.dim() - normalized_shape.size(); i++) stat_shape.push_back(work.size(i));
  for (size_t i = 0; i < normalized_shape.size(); i++) stat_shape.push_back(1);

  auto out = at::empty_like(work);
  auto rstd = at::empty(stat_shape, work.options());

  std::vector<const uint8_t*> ptrs = {
      reinterpret_cast<const uint8_t*>(work.data_ptr())
  };

  uint32_t has_w = 0;
  at::Tensor dummy_w = at::empty({0}, work.options());
  at::Tensor w_contig;

  if (weight_opt.has_value()) {
      has_w = 1;
      w_contig = weight_opt.value().contiguous();
      ptrs.push_back(reinterpret_cast<const uint8_t*>(w_contig.data_ptr()));
  } else {
      ptrs.push_back(reinterpret_cast<const uint8_t*>(dummy_w.data_ptr()));
  }
  ptrs.push_back(reinterpret_cast<const uint8_t*>(out.data_ptr()));
  ptrs.push_back(reinterpret_cast<const uint8_t*>(rstd.data_ptr()));

  RMSNormPushConstants pc = {
      static_cast<uint32_t>(outer_size),
      static_cast<uint32_t>(dim_size),
      static_cast<float>(eps),
      has_w
  };

  int32_t result = vkc_dispatch(
      reinterpret_cast<void*>(it->second),
      ptrs.data(), ptrs.size(),
      outer_size, 1, 1,
      reinterpret_cast<const uint8_t*>(&pc), sizeof(pc));

  TORCH_CHECK(result == 0, "rmsnorm_vulkan dispatch failed");

  return std::make_tuple(out, rstd);
}

std::tuple<at::Tensor, at::Tensor> fused_rms_norm_vulkan(
    const at::Tensor& input,
    c10::IntArrayRef normalized_shape,
    const std::optional<at::Tensor>& weight_opt,
    std::optional<double> eps) {
  return native_rmsnorm_vulkan(input, normalized_shape, weight_opt, eps.value_or(1e-5));
}

std::tuple<at::Tensor, at::Tensor, at::Tensor> native_rms_norm_backward_vulkan(
    const at::Tensor& grad_out, const at::Tensor& input,
    at::IntArrayRef normalized_shape, const at::Tensor& rstd,
    const std::optional<at::Tensor>& weight_opt, const std::optional<at::Tensor>& bias_opt,
    std::array<bool, 3> output_mask);

std::tuple<at::Tensor, at::Tensor> fused_rms_norm_backward_vulkan(
    const at::Tensor& grad_out, const at::Tensor& input,
    c10::IntArrayRef normalized_shape, const at::Tensor& rstd,
    const std::optional<at::Tensor>& weight_opt,
    std::array<bool, 2> output_mask) {
  std::array<bool, 3> expanded_mask = {output_mask[0], output_mask[1], false};
  auto res = native_rms_norm_backward_vulkan(
      grad_out, input, normalized_shape, rstd, weight_opt, std::nullopt, expanded_mask);
  return std::make_tuple(std::get<0>(res), std::get<1>(res));
}

#pragma pack(push, 1)
struct RoPEPushConstants {
    uint32_t num_elements;
    uint32_t D;
    uint32_t S;
    uint32_t H;
};
#pragma pack(pop)


std::tuple<at::Tensor, at::Tensor, at::Tensor> native_layer_norm_backward_vulkan(
    const at::Tensor& grad_out, const at::Tensor& input,
    at::IntArrayRef normalized_shape, const at::Tensor& mean,
    const at::Tensor& rstd, const std::optional<at::Tensor>& weight_opt,
    const std::optional<at::Tensor>& bias_opt, std::array<bool, 3> output_mask) {
  vkc_flush();
  auto w = weight_opt.has_value() ? std::make_optional(weight_opt.value().cpu()) : std::nullopt;
  auto b = bias_opt.has_value() ? std::make_optional(bias_opt.value().cpu()) : std::nullopt;
  auto res = at::native_layer_norm_backward(
      grad_out.cpu(), input.cpu(), normalized_shape, mean.cpu(), rstd.cpu(), w, b, output_mask);
  return std::make_tuple(
      std::get<0>(res).defined() ? std::get<0>(res).to(input.options()) : at::Tensor(),
      std::get<1>(res).defined() ? std::get<1>(res).to(input.options()) : at::Tensor(),
      std::get<2>(res).defined() ? std::get<2>(res).to(input.options()) : at::Tensor());
}

std::tuple<at::Tensor, at::Tensor, at::Tensor> native_rms_norm_backward_vulkan(
    const at::Tensor& grad_out, const at::Tensor& input,
    at::IntArrayRef normalized_shape, const at::Tensor& rstd,
    const std::optional<at::Tensor>& weight_opt, const std::optional<at::Tensor>& bias_opt,
    std::array<bool, 3> output_mask) {
  
  auto grad_out_c = grad_out.contiguous();
  auto input_c = input.contiguous();
  auto rstd_c = rstd.contiguous();
  
  int64_t ndim = input_c.dim();
  int64_t d = ndim - normalized_shape.size();
  
  at::Tensor grad_input;
  at::Tensor grad_weight;
  
  at::Tensor gw_x;
  if (weight_opt.has_value() && weight_opt.value().defined()) {
      auto w = weight_opt.value().contiguous();
      gw_x = grad_out_c * w;
      
      if (output_mask[1]) {
          auto g_w_unreduced = grad_out_c * input_c * rstd_c;
          std::vector<int64_t> reduce_dims;
          for (int64_t i = 0; i < d; i++) reduce_dims.push_back(i);
          grad_weight = g_w_unreduced.sum(reduce_dims);
      }
  } else {
      gw_x = grad_out_c;
  }
  
  if (output_mask[0]) {
      auto term1 = gw_x * rstd_c;
      std::vector<int64_t> reduce_dims;
      for (int64_t i = d; i < ndim; i++) reduce_dims.push_back(i);
      auto dot = (gw_x * input_c).mean(reduce_dims, true);
      auto term2 = input_c * at::pow(rstd_c, 3) * dot;
      grad_input = term1 - term2;
  }
  
  return std::make_tuple(
      output_mask[0] ? grad_input : at::Tensor(),
      output_mask[1] ? grad_weight : at::Tensor(),
      at::Tensor());
}

at::Tensor rope_vulkan(
    const at::Tensor& input,
    const at::Tensor& cos,
    const at::Tensor& sin) {

  auto it = find_shader_for_dtype("rope", input.scalar_type());
  if (it == g_shader_handles.end()) {
    vkc_flush();
    // No exact native PyTorch single-op for RoPE exists universally with this signature, 
    // so we'd have to construct it. For now, just throw if shader missing.
    TORCH_CHECK(false, "rope_vulkan: shader 'rope' not loaded");
  }

  // input: [B, S, H, D]
  TORCH_CHECK(input.dim() >= 3, "rope_vulkan: expected at least 3D tensor");
  
  uint32_t D = input.size(-1);
  uint32_t H = input.dim() >= 4 ? input.size(-2) : 1;
  uint32_t S = input.dim() >= 4 ? input.size(-3) : input.size(-2);
  uint32_t num_elements = input.numel();
  
  auto out = at::empty_like(input);
  
  std::vector<const uint8_t*> ptrs = {
      reinterpret_cast<const uint8_t*>(input.data_ptr()),
      reinterpret_cast<const uint8_t*>(cos.data_ptr()),
      reinterpret_cast<const uint8_t*>(sin.data_ptr()),
      reinterpret_cast<const uint8_t*>(out.data_ptr())
  };

  RoPEPushConstants pc = { num_elements, D, S, H };
  uint32_t groups_x = (num_elements + 255) / 256;

  int32_t result = vkc_dispatch(
      reinterpret_cast<void*>(it->second),
      ptrs.data(), ptrs.size(),
      groups_x, 1, 1,
      reinterpret_cast<const uint8_t*>(&pc), sizeof(pc));

  TORCH_CHECK(result == 0, "rope_vulkan dispatch failed");
  return out;
}

// ---------------------------------------------------------------------------
// Matrix ops (different push constant packing)
// ---------------------------------------------------------------------------

// Cooperative matrix matmul dispatch for f16 inputs -> f32 output.
// Used by both mm and bmm when inputs are float16.
// Requires M, N, K to be multiples of 16 (tile size).
static at::Tensor coopmat_dispatch(
    const at::Tensor& a, const at::Tensor& b,
    uint32_t B, uint32_t M, uint32_t N, uint32_t K) {
  auto it = g_shader_handles.find("bmm_coopmat");
  // Cooperative matrix loads read full 16x16 tiles; non-aligned sizes
  // read past buffer boundaries. Fall back for non-aligned dims.
  if (it == g_shader_handles.end() || M % 16 != 0 || N % 16 != 0 || K % 16 != 0) {
    return {};  // signal fallback needed
  }

  // Coopmat shader: f16 inputs, f16 accumulator output.
  auto out = at::empty(
      B > 1 ? std::vector<int64_t>{B, M, N} : std::vector<int64_t>{M, N},
      a.options());

  // Push constants: Batch, M, N, K
  uint32_t pc[4] = {B, M, N, K};

  std::vector<const uint8_t*> ptrs = {
      reinterpret_cast<const uint8_t*>(a.data_ptr()),
      reinterpret_cast<const uint8_t*>(b.data_ptr()),
      reinterpret_cast<const uint8_t*>(out.data_ptr())};

  uint32_t groups_x = (N + 15) / 16;
  uint32_t groups_y = (M + 15) / 16;

  int32_t result = vkc_dispatch(
      reinterpret_cast<void*>(it->second),
      ptrs.data(), ptrs.size(),
      groups_x, groups_y, B,
      reinterpret_cast<const uint8_t*>(pc), sizeof(pc));

  if (result != 0) return {};

  return out;
}

at::Tensor mm_vulkan(const at::Tensor& self, const at::Tensor& mat2) {
  if (!both_vulkan(self, mat2) || self.dim() != 2 || mat2.dim() != 2 ||
      self.size(1) != mat2.size(0)) {
    vkc_flush();
    return at::mm(self.cpu(), mat2.cpu()).to(self.options());
  }

  // F16: try cooperative matrix (Tensor Core) path first.
  if (self.scalar_type() == c10::ScalarType::Half) {
    auto self_c = self.contiguous();
    auto mat2_c = mat2.contiguous();

    auto result = coopmat_dispatch(
        self_c, mat2_c,
        1, self_c.size(0), mat2_c.size(1), self_c.size(1));
    if (result.defined()) return result;

    // Fall back to tiled f16 shader if dimensions aren't aligned.
    auto it_f16 = g_shader_handles.find("matmul_tiled_f16");
    if (it_f16 != g_shader_handles.end()) {
        uint32_t M = self_c.size(0);
        uint32_t K = self_c.size(1);
        uint32_t N = mat2_c.size(1);
        auto out = at::empty({M, N}, self.options());
        uint32_t pc[3] = {M, N, K};
        std::vector<const uint8_t*> ptrs = {
            reinterpret_cast<const uint8_t*>(self_c.data_ptr()),
            reinterpret_cast<const uint8_t*>(mat2_c.data_ptr()),
            reinterpret_cast<const uint8_t*>(out.data_ptr())};
        uint32_t groups_x = (N + 15) / 16;
        uint32_t groups_y = (M + 15) / 16;
        int32_t res = vkc_dispatch(reinterpret_cast<void*>(it_f16->second), ptrs.data(), ptrs.size(), groups_x, groups_y, 1, reinterpret_cast<const uint8_t*>(pc), sizeof(pc));
        if (res == 0) return out;
    }
    
    vkc_flush();
    return at::mm(self.cpu(), mat2.cpu()).to(self.options());
  }

  // F32: use tiled matmul shader.
  auto it = g_shader_handles.find("matmul_tiled");
  if (it == g_shader_handles.end()) {
    vkc_flush();
    return at::mm(self.cpu(), mat2.cpu()).to(self.options());
  }

  auto self_c = self.contiguous();
  auto mat2_c = mat2.contiguous();

  uint32_t M = self_c.size(0);
  uint32_t K = self_c.size(1);
  uint32_t N = mat2_c.size(1);

  auto out = at::empty({M, N}, self.options());

  uint32_t pc[3] = {M, N, K};

  std::vector<const uint8_t*> ptrs = {
      reinterpret_cast<const uint8_t*>(self_c.data_ptr()),
      reinterpret_cast<const uint8_t*>(mat2_c.data_ptr()),
      reinterpret_cast<const uint8_t*>(out.data_ptr())};

  uint32_t groups_x = (N + 15) / 16;
  uint32_t groups_y = (M + 15) / 16;

  int32_t result = vkc_dispatch(
      reinterpret_cast<void*>(it->second),
      ptrs.data(), ptrs.size(),
      groups_x, groups_y, 1,
      reinterpret_cast<const uint8_t*>(pc), sizeof(pc));

  TORCH_CHECK(result == 0, "mm_vulkan dispatch failed");
  return out;
}

at::Tensor bmm_vulkan(const at::Tensor& self, const at::Tensor& mat2) {
  if (!both_vulkan(self, mat2) || self.dim() != 3 || mat2.dim() != 3 ||
      self.size(0) != mat2.size(0) || self.size(2) != mat2.size(1)) {
    vkc_flush();
    return at::bmm(self.cpu(), mat2.cpu()).to(self.options());
  }

  // F16: use cooperative matrix (Tensor Core) path.
  if (self.scalar_type() == c10::ScalarType::Half) {
    auto self_c = self.contiguous();
    auto mat2_c = mat2.contiguous();
    auto result = coopmat_dispatch(
        self_c, mat2_c,
        self_c.size(0), self_c.size(1), mat2_c.size(2), self_c.size(2));
    if (result.defined()) return result;
    vkc_flush();
    return at::bmm(self.cpu(), mat2.cpu()).to(self.options());
  }

  // F32: use standard bmm shader.
  auto it = g_shader_handles.find("bmm");
  if (it == g_shader_handles.end()) {
    vkc_flush();
    return at::bmm(self.cpu(), mat2.cpu()).to(self.options());
  }

  TORCH_CHECK(self.dim() == 3 && mat2.dim() == 3,
              "bmm_vulkan: expected 3D tensors");

  auto self_c = self.contiguous();
  auto mat2_c = mat2.contiguous();

  uint32_t B = self_c.size(0);
  uint32_t M = self_c.size(1);
  uint32_t K = self_c.size(2);
  uint32_t N = mat2_c.size(2);

  auto out = at::empty({B, M, N}, self.options());

  // Push constants: Batch, M, N, K (4 x uint32)
  uint32_t pc[4] = {B, M, N, K};

  std::vector<const uint8_t*> ptrs = {
      reinterpret_cast<const uint8_t*>(self_c.data_ptr()),
      reinterpret_cast<const uint8_t*>(mat2_c.data_ptr()),
      reinterpret_cast<const uint8_t*>(out.data_ptr())};

  // Tile size = 16, dispatch ceil(N/16) x ceil(M/16) x Batch
  uint32_t groups_x = (N + 15) / 16;
  uint32_t groups_y = (M + 15) / 16;
  uint32_t groups_z = B;

  int32_t result = vkc_dispatch(
      reinterpret_cast<void*>(it->second),
      ptrs.data(), ptrs.size(),
      groups_x, groups_y, groups_z,
      reinterpret_cast<const uint8_t*>(pc), sizeof(pc));

  TORCH_CHECK(result == 0, "bmm_vulkan dispatch failed");
  return out;
}

at::Tensor addmm_vulkan(
    const at::Tensor& self,
    const at::Tensor& mat1,
    const at::Tensor& mat2,
    const at::Scalar& beta,
    const at::Scalar& alpha) {
  
  if (!has_vulkan_buffer(self) || !has_vulkan_buffer(mat1) || !has_vulkan_buffer(mat2)) {
    vkc_flush();
    return at::addmm(self.cpu(), mat1.cpu(), mat2.cpu(), beta, alpha).to(self.options());
  }

  auto mm_res = mm_vulkan(mat1, mat2);
  
  if (alpha.toFloat() != 1.0f) {
      vkc_flush();
      return at::addmm(self.cpu(), mat1.cpu(), mat2.cpu(), beta, alpha).to(self.options());
  }

  if (beta.toFloat() == 0.0f) {
      return mm_res;
  }

  if (beta.toFloat() != 1.0f) {
      vkc_flush();
      return at::addmm(self.cpu(), mat1.cpu(), mat2.cpu(), beta, alpha).to(self.options());
  }

  return add_vulkan(mm_res, self, 1.0f);
}

at::Tensor softmax_vulkan(
    const at::Tensor& self, int64_t dim, bool half_to_float) {
  auto it = find_shader_for_dtype("softmax", self.scalar_type());
  if (it == g_shader_handles.end() || !has_vulkan_buffer(self)) {
    vkc_flush();
    return at::_softmax(self.cpu(), dim, half_to_float).to(self.options());
  }

  auto input = self.contiguous();
  auto ndim = input.dim();
  // Normalize negative dim.
  if (dim < 0) dim += ndim;
  TORCH_CHECK(dim >= 0 && dim < ndim, "softmax_vulkan: dim out of range");

  // The shader operates on (outer_size, dim_size) layout where softmax
  // is applied along the last axis. If dim != last, we need to permute.
  bool needs_permute = (dim != ndim - 1);
  at::Tensor work = input;
  if (needs_permute) {
    // Move target dim to last position.
    std::vector<int64_t> perm;
    for (int64_t i = 0; i < ndim; i++) {
      if (i != dim) perm.push_back(i);
    }
    perm.push_back(dim);
    work = input.permute(perm).contiguous();
  }

  uint32_t dim_size = work.size(ndim - 1);
  uint32_t outer_size = work.numel() / dim_size;

  auto out = at::empty_like(work);
  if (self.scalar_type() == c10::ScalarType::BFloat16) {
      out.fill_(0); // BF16 atomic CAS needs zero initialization
  }

  // Push constants: outer_size, dim_size (2 x uint32)
  uint32_t pc[2] = {outer_size, dim_size};

  std::vector<const uint8_t*> ptrs = {
      reinterpret_cast<const uint8_t*>(work.data_ptr()),
      reinterpret_cast<const uint8_t*>(out.data_ptr())};

  // One workgroup per row.
  int32_t result = vkc_dispatch(
      reinterpret_cast<void*>(it->second),
      ptrs.data(), ptrs.size(),
      outer_size, 1, 1,
      reinterpret_cast<const uint8_t*>(pc), sizeof(pc));

  TORCH_CHECK(result == 0, "softmax_vulkan dispatch failed");

  if (needs_permute) {
    // Inverse permute to restore original dim order.
    std::vector<int64_t> inv_perm(ndim);
    std::vector<int64_t> perm;
    for (int64_t i = 0; i < ndim; i++) {
      if (i != dim) perm.push_back(i);
    }
    perm.push_back(dim);
    for (int64_t i = 0; i < ndim; i++) {
      inv_perm[perm[i]] = i;
    }
    out = out.permute(inv_perm).contiguous();
  }

  return out;
}

at::Tensor softmax_backward_data_vulkan(
    const at::Tensor& grad_output, const at::Tensor& output, int64_t dim, c10::ScalarType input_dtype) {
  auto it = g_shader_handles.find("softmax_backward");
  if (it == g_shader_handles.end() || !has_vulkan_buffer(grad_output) || !has_vulkan_buffer(output)) {
    vkc_flush();
    return at::_softmax_backward_data(grad_output.cpu(), output.cpu(), dim, input_dtype).to(grad_output.options());
  }

  auto grad_out = grad_output.contiguous();
  auto softmax_out = output.contiguous();
  auto ndim = grad_out.dim();
  if (dim < 0) dim += ndim;
  TORCH_CHECK(dim >= 0 && dim < ndim, "softmax_backward_data_vulkan: dim out of range");

  bool needs_permute = (dim != ndim - 1);
  if (needs_permute) {
    std::vector<int64_t> perm;
    for (int64_t i = 0; i < ndim; i++) {
      if (i != dim) perm.push_back(i);
    }
    perm.push_back(dim);
    grad_out = grad_out.permute(perm).contiguous();
    softmax_out = softmax_out.permute(perm).contiguous();
  }

  uint32_t dim_size = grad_out.size(ndim - 1);
  uint32_t outer_size = grad_out.numel() / dim_size;

  auto grad_in = at::empty_like(grad_out);

  uint32_t pc[2] = {outer_size, dim_size};

  std::vector<const uint8_t*> ptrs = {
      reinterpret_cast<const uint8_t*>(grad_out.data_ptr()),
      reinterpret_cast<const uint8_t*>(softmax_out.data_ptr()),
      reinterpret_cast<const uint8_t*>(grad_in.data_ptr())};

  int32_t result = vkc_dispatch(
      reinterpret_cast<void*>(it->second),
      ptrs.data(), ptrs.size(),
      outer_size, 1, 1,
      reinterpret_cast<const uint8_t*>(pc), sizeof(pc));

  TORCH_CHECK(result == 0, "softmax_backward_data_vulkan dispatch failed");

  if (needs_permute) {
    std::vector<int64_t> inv_perm(ndim);
    std::vector<int64_t> perm;
    for (int64_t i = 0; i < ndim; i++) {
      if (i != dim) perm.push_back(i);
    }
    perm.push_back(dim);
    for (int64_t i = 0; i < ndim; i++) {
      inv_perm[perm[i]] = i;
    }
    grad_in = grad_in.permute(inv_perm).contiguous();
  }

  return grad_in;
}

at::Tensor& softmax_backward_data_out_vulkan(
    const at::Tensor& grad_output, const at::Tensor& output, int64_t dim, c10::ScalarType input_dtype, at::Tensor& grad_input) {
  auto it = g_shader_handles.find("softmax_backward");
  if (it == g_shader_handles.end() || !has_vulkan_buffer(grad_output) || !has_vulkan_buffer(output) || !has_vulkan_buffer(grad_input)) {
    vkc_flush();
    auto go_cpu = at::from_blob(const_cast<void*>(grad_output.data_ptr()), grad_output.sizes(), grad_output.strides(), at::TensorOptions().dtype(grad_output.scalar_type()).device(c10::kCPU));
    auto o_cpu = at::from_blob(const_cast<void*>(output.data_ptr()), output.sizes(), output.strides(), at::TensorOptions().dtype(output.scalar_type()).device(c10::kCPU));
    auto gi_cpu = at::from_blob(grad_input.data_ptr(), grad_input.sizes(), grad_input.strides(), at::TensorOptions().dtype(grad_input.scalar_type()).device(c10::kCPU));
    at::_softmax_backward_data_out(gi_cpu, go_cpu, o_cpu, dim, input_dtype);
    return grad_input;
  }

  auto grad_out = grad_output.contiguous();
  auto softmax_out = output.contiguous();
  auto ndim = grad_out.dim();
  if (dim < 0) dim += ndim;
  TORCH_CHECK(dim >= 0 && dim < ndim, "softmax_backward_data_out_vulkan: dim out of range");

  bool needs_permute = (dim != ndim - 1);
  if (needs_permute) {
    std::vector<int64_t> perm;
    for (int64_t i = 0; i < ndim; i++) {
      if (i != dim) perm.push_back(i);
    }
    perm.push_back(dim);
    grad_out = grad_out.permute(perm).contiguous();
    softmax_out = softmax_out.permute(perm).contiguous();
  }

  uint32_t dim_size = grad_out.size(ndim - 1);
  uint32_t outer_size = grad_out.numel() / dim_size;

  at::Tensor gi = grad_input;
  if (needs_permute) {
    std::vector<int64_t> perm;
    for (int64_t i = 0; i < ndim; i++) {
      if (i != dim) perm.push_back(i);
    }
    perm.push_back(dim);
    gi = gi.permute(perm).contiguous();
  } else {
    gi = gi.contiguous();
  }

  uint32_t pc[2] = {outer_size, dim_size};

  std::vector<const uint8_t*> ptrs = {
      reinterpret_cast<const uint8_t*>(grad_out.data_ptr()),
      reinterpret_cast<const uint8_t*>(softmax_out.data_ptr()),
      reinterpret_cast<const uint8_t*>(gi.data_ptr())};

  int32_t result = vkc_dispatch(
      reinterpret_cast<void*>(it->second),
      ptrs.data(), ptrs.size(),
      outer_size, 1, 1,
      reinterpret_cast<const uint8_t*>(pc), sizeof(pc));

  TORCH_CHECK(result == 0, "softmax_backward_data_out_vulkan dispatch failed");

  if (!gi.is_same(grad_input)) {
     if (needs_permute) {
       std::vector<int64_t> inv_perm(ndim);
       std::vector<int64_t> perm;
       for (int64_t i = 0; i < ndim; i++) {
         if (i != dim) perm.push_back(i);
       }
       perm.push_back(dim);
       for (int64_t i = 0; i < ndim; i++) {
         inv_perm[perm[i]] = i;
       }
       gi = gi.permute(inv_perm);
     }
     grad_input.copy_(gi);
  }

  return grad_input;
}

// Native transformer encoder layer: decompose into native ops entirely on Vulkan.
// This avoids the massive CPU fallback from the fused _native_multi_head_attention.
at::Tensor transformer_encoder_layer_fwd_vulkan(
    const at::Tensor& src,
    int64_t embed_dim,
    int64_t num_heads,
    const at::Tensor& qkv_weight,
    const at::Tensor& qkv_bias,
    const at::Tensor& proj_weight,
    const at::Tensor& proj_bias,
    bool use_gelu,
    bool norm_first,
    double eps,
    const at::Tensor& norm_weight_1,
    const at::Tensor& norm_bias_1,
    const at::Tensor& norm_weight_2,
    const at::Tensor& norm_bias_2,
    const at::Tensor& ffn_weight_1,
    const at::Tensor& ffn_bias_1,
    const at::Tensor& ffn_weight_2,
    const at::Tensor& ffn_bias_2,
    const std::optional<at::Tensor>& mask,
    std::optional<int64_t> mask_type) {

  if (!is_vulkan(src)) {
    vkc_flush();
    return at::_transformer_encoder_layer_fwd(
        src.cpu(), embed_dim, num_heads,
        qkv_weight.cpu(), qkv_bias.cpu(),
        proj_weight.cpu(), proj_bias.cpu(),
        use_gelu, norm_first, eps,
        norm_weight_1.cpu(), norm_bias_1.cpu(),
        norm_weight_2.cpu(), norm_bias_2.cpu(),
        ffn_weight_1.cpu(), ffn_bias_1.cpu(),
        ffn_weight_2.cpu(), ffn_bias_2.cpu(),
        mask.has_value() ? std::make_optional(mask.value().cpu()) : std::nullopt,
        mask_type).to(src.options());
  }

  int64_t B = src.size(0);
  int64_t S = src.size(1);
  int64_t head_dim = embed_dim / num_heads;

  auto x = src;

  // Pre-norm or post-norm path.
  auto normed = norm_first
      ? at::layer_norm(x, {embed_dim}, norm_weight_1, norm_bias_1, eps)
      : x;

  // QKV projection: (B*S, E) @ (3E, E)^T + bias -> (B*S, 3E)
  auto qkv_flat = at::addmm(qkv_bias, normed.view({B * S, embed_dim}), qkv_weight.t());

  // Reshape to (B, S, 3, H, D) then chunk along dim=2 into Q, K, V
  // Use narrow + reshape to avoid permute+contiguous copies.
  auto qkv_3 = qkv_flat.view({B, S, 3, embed_dim});
  auto q_flat = qkv_3.select(2, 0).view({B, S, num_heads, head_dim}).transpose(1, 2);
  auto k_flat = qkv_3.select(2, 1).view({B, S, num_heads, head_dim}).transpose(1, 2);
  auto v_flat = qkv_3.select(2, 2).view({B, S, num_heads, head_dim}).transpose(1, 2);

  // SDPA works on non-contiguous views via our bmm which calls contiguous internally.
  float scale = 1.0f / std::sqrt(static_cast<float>(head_dim));
  auto attn_scores = at::matmul(q_flat, k_flat.transpose(-2, -1)) * scale;
  attn_scores = at::softmax(attn_scores, -1);
  auto attn_out = at::matmul(attn_scores, v_flat);

  // Reshape back: (B, H, S, D) -> (B, S, E) - transpose + view
  attn_out = attn_out.transpose(1, 2).contiguous().view({B, S, embed_dim});

  // Output projection
  auto proj_out = at::addmm(proj_bias, attn_out.view({B * S, embed_dim}), proj_weight.t())
      .view({B, S, embed_dim});

  // First residual + norm
  if (norm_first) {
    x = x + proj_out;
  } else {
    x = at::layer_norm(x + proj_out, {embed_dim}, norm_weight_1, norm_bias_1, eps);
  }

  // FFN
  auto ffn_normed = norm_first
      ? at::layer_norm(x, {embed_dim}, norm_weight_2, norm_bias_2, eps)
      : x;

  auto ffn = at::addmm(ffn_bias_1, ffn_normed.view({B * S, embed_dim}), ffn_weight_1.t())
      .view({B, S, -1});
  ffn = use_gelu ? at::gelu(ffn) : at::relu(ffn);
  ffn = at::addmm(ffn_bias_2, ffn.view({B * S, ffn.size(-1)}), ffn_weight_2.t())
      .view({B, S, embed_dim});

  // Second residual + norm
  if (norm_first) {
    x = x + ffn;
  } else {
    x = at::layer_norm(x + ffn, {embed_dim}, norm_weight_2, norm_bias_2, eps);
  }

  return x;
}

// Native SDPA: decompose into bmm + softmax + bmm on Vulkan.
// This intercepts nn.MultiheadAttention's SDPA call and keeps it on-device
// instead of falling back to CPU via _native_multi_head_attention.
at::Tensor sdpa_vulkan(
    const at::Tensor& query,
    const at::Tensor& key,
    const at::Tensor& value,
    const std::optional<at::Tensor>& attn_mask,
    double dropout_p,
    bool is_causal,
    std::optional<double> scale,
    bool enable_gqa) {

  // For complex cases (masking, dropout, causal, GQA), fall back to CPU.
  if (attn_mask.has_value() || dropout_p > 0.0 || is_causal || enable_gqa ||
      !is_vulkan(query)) {
    vkc_flush();
    auto q = query.cpu(), k = key.cpu(), v = value.cpu();
    auto mask = attn_mask.has_value()
        ? std::make_optional(attn_mask.value().cpu()) : std::nullopt;
    return at::scaled_dot_product_attention(
        q, k, v, mask, dropout_p, is_causal, scale, enable_gqa)
        .to(query.options());
  }

  // Decomposed SDPA: Q @ K^T * scale -> softmax -> @ V
  // query/key/value: (B, H, S, D) or (B*H, S, D)
  float s = scale.has_value()
      ? static_cast<float>(scale.value())
      : (1.0f / std::sqrt(static_cast<float>(query.size(-1))));

  auto scores = at::matmul(query, key.transpose(-2, -1)) * s;
  scores = at::softmax(scores, -1);
  return at::matmul(scores, value);
}

// ---------------------------------------------------------------------------
// PrivateUse1 Hooks
// ---------------------------------------------------------------------------

struct VulkanPrivateUse1Hooks : public at::PrivateUse1HooksInterface {
  bool hasPrimaryContext(c10::DeviceIndex device_index) const override {
    return true;
  }
};

static struct RegisterVulkanHooks {
  RegisterVulkanHooks() {
    static VulkanPrivateUse1Hooks hooks;
    at::RegisterPrivateUse1HooksInterface(&hooks);
  }
} g_register_vulkan_hooks;

// ---------------------------------------------------------------------------
// Tensor factory ops registered on PrivateUse1
// ---------------------------------------------------------------------------

at::Tensor empty_vulkan(
    c10::IntArrayRef size,
    std::optional<c10::ScalarType> dtype,
    std::optional<c10::Layout> layout,
    std::optional<c10::Device> device,
    std::optional<bool> pin_memory,
    std::optional<c10::MemoryFormat> memory_format) {
  auto actual_dtype = dtype.value_or(c10::ScalarType::Float);
  auto nbytes = c10::multiply_integers(size) * c10::elementSize(actual_dtype);

  void* handle = nullptr;
  uint8_t* ptr = vkc_alloc(nbytes, &handle);
  if (!ptr && nbytes > 0) {
    throw std::runtime_error("Vulkan empty: allocation failed");
  }

  auto storage = c10::Storage(
      c10::Storage::use_byte_size_t(),
      static_cast<int64_t>(nbytes),
      c10::DataPtr(ptr, handle, &RustVulkanAllocator::raw_delete,
                   c10::Device(c10::DeviceType::PrivateUse1, 0)),
      /*allocator=*/nullptr,
      /*resizable=*/false);

  auto tensor = at::detail::make_tensor<c10::TensorImpl>(
      std::move(storage),
      c10::DispatchKeySet(c10::DispatchKey::PrivateUse1),
      c10::scalarTypeToTypeMeta(actual_dtype));
  tensor.unsafeGetTensorImpl()->set_sizes_contiguous(size);
  return tensor;
}

#pragma pack(push, 1)
struct CopyPushConstants {
    uint32_t num_elements;
    uint32_t ndim;
    uint32_t size0; uint32_t size1; uint32_t size2; uint32_t size3;
    uint32_t src_stride0; uint32_t src_stride1; uint32_t src_stride2; uint32_t src_stride3;
    uint32_t src_offset;
    uint32_t dst_stride0; uint32_t dst_stride1; uint32_t dst_stride2; uint32_t dst_stride3;
    uint32_t dst_offset;
};
#pragma pack(pop)

at::Tensor& copy_vulkan_(at::Tensor& self, const at::Tensor& src, bool non_blocking) {
  bool self_vk = has_vulkan_buffer(self);
  bool src_vk = has_vulkan_buffer(src);

  // Fast path: contiguous same-dtype where at least one side is Vulkan.
  if (self.is_contiguous() && src.is_contiguous() && self.dtype() == src.dtype()
      && self.nbytes() == src.nbytes()) {
    if (self_vk && src_vk) {
        int32_t result = vkc_copy_buffer(
            reinterpret_cast<const uint8_t*>(src.data_ptr()),
            reinterpret_cast<const uint8_t*>(self.data_ptr()),
            self.nbytes());
        TORCH_CHECK(result == 0, "vkc_copy_buffer failed");
    } else {
        // CPU-GPU or GPU-CPU copy. Need to flush pending commands to prevent data races.
        vkc_flush();
        std::memcpy(self.data_ptr(), src.data_ptr(), self.nbytes());
    }
    return self;
  }

  // Both on Vulkan: try async GPU copy shader (supports dtype cast and strided)
  if (self_vk && src_vk) {
      std::string shader_name = "copy";
      if (self.scalar_type() == c10::kHalf && src.scalar_type() == c10::kHalf) {
          shader_name = "copy_f16";
      } else if (self.scalar_type() == c10::kBFloat16 && src.scalar_type() == c10::kBFloat16) {
          shader_name = "copy_bf16";
      } else if (self.scalar_type() == c10::kFloat && src.scalar_type() == c10::kHalf) {
          shader_name = "copy_f16_to_f32";
      } else if (self.scalar_type() == c10::kHalf && src.scalar_type() == c10::kFloat) {
          shader_name = "copy_f32_to_f16";
      }

      auto it = g_shader_handles.find(shader_name);
      if (it != g_shader_handles.end() && self.dim() <= 4) {
          uint32_t num_elements = self.numel();
          uint32_t ndim = self.dim();
          CopyPushConstants pc = {num_elements, ndim, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
          
          pc.src_offset = src.storage_offset(); 
          pc.dst_offset = self.storage_offset();
          
          uint32_t s_sizes[4] = {1, 1, 1, 1};
          uint32_t s_src_strides[4] = {0, 0, 0, 0};
          uint32_t s_dst_strides[4] = {0, 0, 0, 0};
          
          int offset = 4 - ndim;
          for (int i = 0; i < ndim; i++) {
              s_sizes[offset + i] = self.size(i);
              s_src_strides[offset + i] = src.stride(i);
              s_dst_strides[offset + i] = self.stride(i);
          }
          
          pc.size0 = s_sizes[0]; pc.size1 = s_sizes[1]; pc.size2 = s_sizes[2]; pc.size3 = s_sizes[3];
          pc.src_stride0 = s_src_strides[0]; pc.src_stride1 = s_src_strides[1]; pc.src_stride2 = s_src_strides[2]; pc.src_stride3 = s_src_strides[3];
          pc.dst_stride0 = s_dst_strides[0]; pc.dst_stride1 = s_dst_strides[1]; pc.dst_stride2 = s_dst_strides[2]; pc.dst_stride3 = s_dst_strides[3];

          std::vector<const uint8_t*> ptrs = {
              reinterpret_cast<const uint8_t*>(src.storage().data_ptr().get()),
              reinterpret_cast<const uint8_t*>(self.storage().data_ptr().get())
          };
          
          uint32_t groups_x = (num_elements + 255) / 256;
          
          int32_t result = vkc_dispatch(
              reinterpret_cast<void*>(it->second),
              ptrs.data(), ptrs.size(),
              groups_x, 1, 1,
              reinterpret_cast<const uint8_t*>(&pc), sizeof(pc));
              
          if (result == 0) return self;
      }
  }

  // Mixed device: CPU fallback via from_blob.
  vkc_flush();
  auto cpu_options = at::TensorOptions().dtype(self.scalar_type()).device(c10::kCPU);

  at::Tensor safe_src = src;
  if (src.device().type() != c10::DeviceType::CPU && !src_vk) {
      safe_src = src.cpu();
  }

  auto src_cpu_options = at::TensorOptions().dtype(safe_src.scalar_type()).device(c10::kCPU);
  auto self_cpu = at::from_blob(self.data_ptr(), self.sizes(), self.strides(), cpu_options);
  auto src_cpu = at::from_blob(const_cast<void*>(safe_src.data_ptr()), safe_src.sizes(), safe_src.strides(), src_cpu_options);
  self_cpu.copy_(src_cpu, non_blocking);
  return self;
}
at::Tensor empty_strided_vulkan(
    c10::IntArrayRef size,
    c10::IntArrayRef stride,
    std::optional<c10::ScalarType> dtype,
    std::optional<c10::Layout> layout,
    std::optional<c10::Device> device,
    std::optional<bool> pin_memory) {
  // For now, ignore strides and create contiguous. Most ops work with contiguous.
  return empty_vulkan(size, dtype, layout, device, pin_memory, c10::MemoryFormat::Contiguous);
}

at::Tensor& fill_vulkan_(at::Tensor& self, const at::Scalar& value) {
  // If the value is 0.0, we can use the async Vulkan fill command
  if (value.toFloat() == 0.0f) {
    vkc_fill_buffer(reinterpret_cast<const uint8_t*>(self.data_ptr()), self.nbytes(), 0);
    return self;
  }

  // Otherwise, fallback to CPU synchronous fill
  vkc_flush();
  float val = value.toFloat();
  if (self.scalar_type() == c10::ScalarType::Float) {
      float* ptr = static_cast<float*>(self.data_ptr());
      for (int64_t i = 0; i < self.numel(); i++) ptr[i] = val;
  } else if (self.scalar_type() == c10::ScalarType::Half) {
      at::Half* ptr = static_cast<at::Half*>(self.data_ptr());
      for (int64_t i = 0; i < self.numel(); i++) ptr[i] = static_cast<at::Half>(val);
  } else if (self.scalar_type() == c10::ScalarType::BFloat16) {
      at::BFloat16* ptr = static_cast<at::BFloat16*>(self.data_ptr());
      for (int64_t i = 0; i < self.numel(); i++) ptr[i] = static_cast<at::BFloat16>(val);
  } else {
      // Fallback
      auto self_cpu = at::from_blob(self.data_ptr(), self.sizes(), self.strides(), at::TensorOptions().dtype(self.scalar_type()).device(c10::kCPU));
      self_cpu.fill_(value);
  }
  return self;
}

at::Tensor& zero_vulkan_(at::Tensor& self) {
  vkc_fill_buffer(reinterpret_cast<const uint8_t*>(self.data_ptr()), self.nbytes(), 0);
  return self;
}

at::Tensor& normal_vulkan_(at::Tensor& self, double mean, double std, std::optional<at::Generator> gen) {
  // Generate on CPU then copy (host-mapped buffer so memcpy works).
  auto cpu_tensor = at::empty(self.sizes(), self.options().device(c10::kCPU));
  cpu_tensor.normal_(mean, std, gen);
  std::memcpy(self.data_ptr(), cpu_tensor.data_ptr(), self.nbytes());
  return self;
}

at::Tensor& uniform_vulkan_(at::Tensor& self, double from, double to, std::optional<at::Generator> gen) {
  auto cpu_tensor = at::empty(self.sizes(), self.options().device(c10::kCPU));
  cpu_tensor.uniform_(from, to, gen);
  std::memcpy(self.data_ptr(), cpu_tensor.data_ptr(), self.nbytes());
  return self;
}

// --- Embedding (index into weight table) ---

at::Tensor embedding_vulkan(
    const at::Tensor& weight, const at::Tensor& indices,
    int64_t padding_idx, bool scale_grad_by_freq, bool sparse) {
  auto it = find_shader_for_dtype("embedding", weight.scalar_type());
  if (it != g_shader_handles.end() && has_vulkan_buffer(weight) &&
      has_vulkan_buffer(indices) && weight.is_contiguous() &&
      indices.is_contiguous()) {
    uint32_t num_indices = indices.numel();
    uint32_t embedding_dim = weight.size(1);
    uint32_t total_elements = num_indices * embedding_dim;

    // Convert indices to int32 (shader expects 32-bit int, PyTorch uses int64)
    auto indices_i32 = indices.to(c10::ScalarType::Int).contiguous();

    auto out_sizes = indices.sizes().vec();
    out_sizes.push_back(embedding_dim);
    auto out = at::empty(out_sizes, weight.options());

    struct { uint32_t n; uint32_t d; } pc = {num_indices, embedding_dim};

    std::vector<const uint8_t*> ptrs = {
        reinterpret_cast<const uint8_t*>(weight.data_ptr()),
        reinterpret_cast<const uint8_t*>(indices_i32.data_ptr()),
        reinterpret_cast<const uint8_t*>(out.data_ptr())};

    uint32_t groups_x = (total_elements + 255) / 256;
    int32_t result = vkc_dispatch(
        reinterpret_cast<void*>(it->second),
        ptrs.data(), ptrs.size(),
        groups_x, 1, 1,
        reinterpret_cast<const uint8_t*>(&pc), sizeof(pc));

    if (result == 0) return out;
  }

  // Fallback: CPU embedding
  vkc_flush();
  auto weight_cpu = at::empty(weight.sizes(), weight.options().device(c10::kCPU));
  std::memcpy(weight_cpu.data_ptr(), weight.data_ptr(), weight.nbytes());
  auto indices_cpu = at::empty(indices.sizes(), indices.options().device(c10::kCPU));
  std::memcpy(indices_cpu.data_ptr(), indices.data_ptr(), indices.nbytes());
  auto result_cpu = at::embedding(weight_cpu, indices_cpu, padding_idx, scale_grad_by_freq, sparse);
  auto out = at::empty(result_cpu.sizes(), weight.options().dtype(result_cpu.scalar_type()));
  std::memcpy(out.data_ptr(), result_cpu.data_ptr(), result_cpu.nbytes());
  return out;
}

at::Tensor embedding_dense_backward_vulkan(
    const at::Tensor& grad_output, const at::Tensor& indices,
    int64_t num_weights, int64_t padding_idx, bool scale_grad_by_freq) {
  // CPU fallback for embedding backward
  vkc_flush();
  auto grad_cpu = grad_output.to(c10::kCPU);
  auto indices_cpu = indices.to(c10::kCPU);
  auto result_cpu = at::embedding_dense_backward(grad_cpu, indices_cpu, num_weights, padding_idx, scale_grad_by_freq);
  return result_cpu.to(grad_output.device());
}

// --- Shape/stride metadata ops (zero-copy) ---

at::Tensor view_vulkan(const at::Tensor& self, at::SymIntArrayRef size) {
  // Resolve symbolic ints to concrete values.
  std::vector<int64_t> concrete_size;
  for (const auto& s : size) {
    concrete_size.push_back(s.expect_int());
  }
  auto inferred = at::infer_size_dv(concrete_size, self.numel());
  auto strides = at::detail::computeStride(self.sizes(), self.strides(), inferred);
  TORCH_CHECK(strides.has_value(),
              "view size is not compatible with input tensor's size and stride");
  auto result = at::detail::make_tensor<c10::TensorImpl>(
      c10::Storage(self.storage()),
      self.key_set(),
      self.dtype());
  result.unsafeGetTensorImpl()->set_storage_offset(self.storage_offset());
  result.unsafeGetTensorImpl()->set_sizes_and_strides(inferred, strides.value());
  return result;
}

at::Tensor _reshape_alias_vulkan(
    const at::Tensor& self, c10::IntArrayRef size, c10::IntArrayRef stride) {
  auto result = at::detail::make_tensor<c10::TensorImpl>(
      c10::Storage(self.storage()),
      self.key_set(),
      self.dtype());
  result.unsafeGetTensorImpl()->set_storage_offset(self.storage_offset());
  result.unsafeGetTensorImpl()->set_sizes_and_strides(size, stride);
  return result;
}

at::Tensor expand_vulkan(const at::Tensor& self, c10::IntArrayRef size, bool implicit) {
  auto expanded = at::inferExpandGeometry_dimvector(self.sizes(), self.strides(), size);
  auto result = self.as_strided(
      expanded.sizes,
      expanded.strides,
      self.storage_offset());
  return result;
}

at::Tensor as_strided_vulkan(
    const at::Tensor& self, c10::IntArrayRef size,
    c10::IntArrayRef stride, std::optional<int64_t> storage_offset) {
  auto result = at::detail::make_tensor<c10::TensorImpl>(
      c10::Storage(self.storage()),
      self.key_set(),
      self.dtype());
  auto offset = storage_offset.value_or(self.storage_offset());
  result.unsafeGetTensorImpl()->set_storage_offset(offset);
  result.unsafeGetTensorImpl()->set_sizes_and_strides(size, stride);
  return result;
}

at::Tensor detach_vulkan(const at::Tensor& self) {
  auto result = at::detail::make_tensor<c10::TensorImpl>(
      c10::Storage(self.storage()),
      c10::DispatchKeySet(c10::DispatchKey::PrivateUse1),
      self.dtype());
  result.unsafeGetTensorImpl()->set_storage_offset(self.storage_offset());
  result.unsafeGetTensorImpl()->set_sizes_and_strides(self.sizes(), self.strides());
  return result;
}

at::Tensor _to_copy_vulkan(
    const at::Tensor& self,
    std::optional<c10::ScalarType> dtype,
    std::optional<c10::Layout> layout,
    std::optional<c10::Device> device,
    std::optional<bool> pin_memory,
    bool non_blocking,
    std::optional<c10::MemoryFormat> memory_format) {
  vkc_flush();
  auto target_dtype = dtype.value_or(self.scalar_type());
  auto target_device = device.value_or(self.device());

  if (target_device.type() == c10::DeviceType::CPU) {
    // Vulkan -> CPU: use from_blob to avoid recursive dispatch.
    auto result = at::empty(self.sizes(), self.options().device(c10::kCPU).dtype(target_dtype));
    if (self.is_contiguous() && result.is_contiguous() &&
        self.scalar_type() == target_dtype) {
      std::memcpy(result.data_ptr(), self.data_ptr(), self.nbytes());
    } else {
      auto src_cpu = at::from_blob(
          const_cast<void*>(self.data_ptr()), self.sizes(), self.strides(),
          at::TensorOptions().dtype(self.scalar_type()).device(c10::kCPU));
      result.copy_(src_cpu, non_blocking);
    }
    return result;
  }

  // Same device copy or CPU->Vulkan.
  auto result = at::empty(self.sizes(),
      self.options().device(target_device).dtype(target_dtype));

  // Direct memcpy for contiguous same-dtype (avoid re-entering dispatcher).
  if (self.is_contiguous() && result.is_contiguous() &&
      self.scalar_type() == target_dtype && self.nbytes() == result.nbytes()) {
    std::memcpy(result.data_ptr(), self.data_ptr(), self.nbytes());
  } else {
    // Non-contiguous: use from_blob to alias as CPU and copy.
    auto cpu_opts = at::TensorOptions().dtype(target_dtype).device(c10::kCPU);
    auto src_cpu_opts = at::TensorOptions().dtype(self.scalar_type()).device(c10::kCPU);
    auto dst_cpu = at::from_blob(result.data_ptr(), result.sizes(), result.strides(), cpu_opts);
    auto src_cpu = at::from_blob(const_cast<void*>(self.data_ptr()), self.sizes(), self.strides(), src_cpu_opts);
    dst_cpu.copy_(src_cpu, non_blocking);
  }
  return result;
}

const at::Tensor& resize_vulkan_(
    const at::Tensor& self,
    c10::IntArrayRef size,
    std::optional<c10::MemoryFormat> optional_memory_format) {
  auto* self_impl = self.unsafeGetTensorImpl();
  int64_t new_numel = c10::multiply_integers(size);
  int64_t new_size_bytes = new_numel * self_impl->dtype().itemsize();

  if (new_size_bytes > self_impl->storage().nbytes()) {
    void* handle = nullptr;
    uint8_t* ptr = vkc_alloc(new_size_bytes, &handle);
    if (!ptr && new_size_bytes > 0) {
      throw std::runtime_error("Vulkan resize: allocation failed");
    }
    auto storage = c10::Storage(
        c10::Storage::use_byte_size_t(),
        static_cast<int64_t>(new_size_bytes),
        c10::DataPtr(ptr, handle, &RustVulkanAllocator::raw_delete,
                     c10::Device(c10::DeviceType::PrivateUse1, 0)),
        &g_allocator,
        /*resizable=*/true);
    self_impl->set_storage_keep_dtype(storage);
  }

  self_impl->set_sizes_contiguous(size);
  return self;
}

at::Tensor _copy_from_and_resize_vulkan(const at::Tensor& self, const at::Tensor& dst) {
  vkc_flush();
  if (dst.sizes() != self.sizes()) {
    resize_vulkan_(dst, self.sizes(), std::nullopt);
  }
  dst.copy_(self);
  return dst;
}

#pragma pack(push, 1)
struct AddcdivPushConstants {
    uint32_t num_elements;
    float value;
};
#pragma pack(pop)

at::Tensor addcdiv_vulkan(const at::Tensor& self, const at::Tensor& tensor1, const at::Tensor& tensor2, const at::Scalar& value) {
  auto it = find_shader_for_dtype("addcdiv", self.scalar_type());
  if (it == g_shader_handles.end() || !has_vulkan_buffer(self) || !has_vulkan_buffer(tensor1) || !has_vulkan_buffer(tensor2)) {
    vkc_flush();
    return at::addcdiv(self.cpu(), tensor1.cpu(), tensor2.cpu(), value).to(self.options());
  }

  auto [t1_b, t2_b] = needs_broadcast(tensor1, tensor2) ? broadcast_operands(tensor1, tensor2) : std::make_pair(tensor1.contiguous(), tensor2.contiguous());
  auto [self_b, _ignore] = needs_broadcast(self, t1_b) ? broadcast_operands(self, t1_b) : std::make_pair(self.contiguous(), t1_b);

  auto out = at::empty_like(self_b);
  uint32_t num_elements = self_b.numel();
  uint32_t groups_x = (num_elements + 255) / 256;

  std::vector<const uint8_t*> ptrs = {
      reinterpret_cast<const uint8_t*>(self_b.data_ptr()),
      reinterpret_cast<const uint8_t*>(t1_b.data_ptr()),
      reinterpret_cast<const uint8_t*>(t2_b.data_ptr()),
      reinterpret_cast<const uint8_t*>(out.data_ptr())};

  AddcdivPushConstants pc = {num_elements, value.toFloat()};

  int32_t result = vkc_dispatch(
      reinterpret_cast<void*>(it->second),
      ptrs.data(), ptrs.size(),
      groups_x, 1, 1,
      reinterpret_cast<const uint8_t*>(&pc), sizeof(pc));

  TORCH_CHECK(result == 0, "addcdiv_vulkan dispatch failed");
  return out;
}

at::Tensor& addcdiv_vulkan_(at::Tensor& self, const at::Tensor& tensor1, const at::Tensor& tensor2, const at::Scalar& value) {
  auto it = find_shader_for_dtype("addcdiv", self.scalar_type());
  if (it == g_shader_handles.end() || !has_vulkan_buffer(self) || !has_vulkan_buffer(tensor1) || !has_vulkan_buffer(tensor2)) {
    vkc_flush();
    auto self_cpu = at::from_blob(self.data_ptr(), self.sizes(), self.strides(), at::TensorOptions().dtype(self.scalar_type()).device(c10::kCPU));
    self_cpu.addcdiv_(tensor1.cpu(), tensor2.cpu(), value);
    return self;
  }

  auto [t1_b, t2_b] = needs_broadcast(tensor1, tensor2) ? broadcast_operands(tensor1, tensor2) : std::make_pair(tensor1.contiguous(), tensor2.contiguous());
  auto [self_b, _ignore] = needs_broadcast(self, t1_b) ? broadcast_operands(self, t1_b) : std::make_pair(self.contiguous(), t1_b);

  uint32_t num_elements = self_b.numel();
  uint32_t groups_x = (num_elements + 255) / 256;

  std::vector<const uint8_t*> ptrs = {
      reinterpret_cast<const uint8_t*>(self_b.data_ptr()),
      reinterpret_cast<const uint8_t*>(t1_b.data_ptr()),
      reinterpret_cast<const uint8_t*>(t2_b.data_ptr()),
      reinterpret_cast<const uint8_t*>(self.data_ptr())};

  AddcdivPushConstants pc = {num_elements, value.toFloat()};

  int32_t result = vkc_dispatch(
      reinterpret_cast<void*>(it->second),
      ptrs.data(), ptrs.size(),
      groups_x, 1, 1,
      reinterpret_cast<const uint8_t*>(&pc), sizeof(pc));

  TORCH_CHECK(result == 0, "addcdiv_vulkan_ dispatch failed");
  return self;
}

#pragma pack(push, 1)
struct AddcmulPushConstants {
    uint32_t num_elements;
    float value;
};
#pragma pack(pop)

at::Tensor addcmul_vulkan(const at::Tensor& self, const at::Tensor& tensor1, const at::Tensor& tensor2, const at::Scalar& value) {
  auto it = find_shader_for_dtype("addcmul", self.scalar_type());
  if (it == g_shader_handles.end() || !has_vulkan_buffer(self) || !has_vulkan_buffer(tensor1) || !has_vulkan_buffer(tensor2)) {
    vkc_flush();
    return at::addcmul(self.cpu(), tensor1.cpu(), tensor2.cpu(), value).to(self.options());
  }

  auto [t1_b, t2_b] = needs_broadcast(tensor1, tensor2) ? broadcast_operands(tensor1, tensor2) : std::make_pair(tensor1.contiguous(), tensor2.contiguous());
  auto [self_b, _ignore] = needs_broadcast(self, t1_b) ? broadcast_operands(self, t1_b) : std::make_pair(self.contiguous(), t1_b);

  auto out = at::empty_like(self_b);
  uint32_t num_elements = self_b.numel();
  uint32_t groups_x = (num_elements + 255) / 256;

  std::vector<const uint8_t*> ptrs = {
      reinterpret_cast<const uint8_t*>(self_b.data_ptr()),
      reinterpret_cast<const uint8_t*>(t1_b.expand(self_b.sizes()).contiguous().data_ptr()),
      reinterpret_cast<const uint8_t*>(t2_b.expand(self_b.sizes()).contiguous().data_ptr()),
      reinterpret_cast<const uint8_t*>(out.data_ptr())};

  AddcmulPushConstants pc = {num_elements, value.toFloat()};

  int32_t result = vkc_dispatch(
      reinterpret_cast<void*>(it->second),
      ptrs.data(), ptrs.size(),
      groups_x, 1, 1,
      reinterpret_cast<const uint8_t*>(&pc), sizeof(pc));

  TORCH_CHECK(result == 0, "addcmul_vulkan dispatch failed");
  return out;
}

at::Tensor& addcmul_vulkan_(at::Tensor& self, const at::Tensor& tensor1, const at::Tensor& tensor2, const at::Scalar& value) {
  auto it = find_shader_for_dtype("addcmul", self.scalar_type());
  if (it == g_shader_handles.end() || !has_vulkan_buffer(self) || !has_vulkan_buffer(tensor1) || !has_vulkan_buffer(tensor2)) {
    vkc_flush();
    auto self_cpu = at::from_blob(self.data_ptr(), self.sizes(), self.strides(), at::TensorOptions().dtype(self.scalar_type()).device(c10::kCPU));
    self_cpu.addcmul_(tensor1.cpu(), tensor2.cpu(), value);
    return self;
  }

  auto t1_b = tensor1.expand(self.sizes()).contiguous();
  auto t2_b = tensor2.expand(self.sizes()).contiguous();
  auto self_b = self.contiguous();

  uint32_t num_elements = self_b.numel();
  uint32_t groups_x = (num_elements + 255) / 256;

  std::vector<const uint8_t*> ptrs = {
      reinterpret_cast<const uint8_t*>(self_b.data_ptr()),
      reinterpret_cast<const uint8_t*>(t1_b.data_ptr()),
      reinterpret_cast<const uint8_t*>(t2_b.data_ptr()),
      reinterpret_cast<const uint8_t*>(self.data_ptr())};

  AddcmulPushConstants pc = {num_elements, value.toFloat()};

  int32_t result = vkc_dispatch(
      reinterpret_cast<void*>(it->second),
      ptrs.data(), ptrs.size(),
      groups_x, 1, 1,
      reinterpret_cast<const uint8_t*>(&pc), sizeof(pc));

  TORCH_CHECK(result == 0, "addcmul_vulkan_ dispatch failed");
  return self;
}

#pragma pack(push, 1)
struct LerpPushConstants {
    uint32_t num_elements;
    float weight;
};
struct LerpTensorPushConstants {
    uint32_t num_elements;
};
#pragma pack(pop)

at::Tensor lerp_vulkan_scalar(const at::Tensor& self, const at::Tensor& end, const at::Scalar& weight) {
  auto it = find_shader_for_dtype("lerp", self.scalar_type());
  if (it == g_shader_handles.end() || !has_vulkan_buffer(self) || !has_vulkan_buffer(end)) {
    vkc_flush();
    return at::lerp(self.cpu(), end.cpu(), weight).to(self.options());
  }

  auto [self_b, end_b] = needs_broadcast(self, end) ? broadcast_operands(self, end) : std::make_pair(self.contiguous(), end.contiguous());

  auto out = at::empty_like(self_b);
  uint32_t num_elements = self_b.numel();
  uint32_t groups_x = (num_elements + 255) / 256;

  std::vector<const uint8_t*> ptrs = {
      reinterpret_cast<const uint8_t*>(self_b.data_ptr()),
      reinterpret_cast<const uint8_t*>(end_b.data_ptr()),
      reinterpret_cast<const uint8_t*>(out.data_ptr())};

  LerpPushConstants pc = {num_elements, weight.toFloat()};

  int32_t result = vkc_dispatch(
      reinterpret_cast<void*>(it->second),
      ptrs.data(), ptrs.size(),
      groups_x, 1, 1,
      reinterpret_cast<const uint8_t*>(&pc), sizeof(pc));

  TORCH_CHECK(result == 0, "lerp_vulkan_scalar dispatch failed");
  return out;
}

at::Tensor& lerp_vulkan_scalar_(at::Tensor& self, const at::Tensor& end, const at::Scalar& weight) {
  auto it = find_shader_for_dtype("lerp", self.scalar_type());
  if (it == g_shader_handles.end() || !has_vulkan_buffer(self) || !has_vulkan_buffer(end)) {
    vkc_flush();
    auto self_cpu = at::from_blob(self.data_ptr(), self.sizes(), self.strides(), at::TensorOptions().dtype(self.scalar_type()).device(c10::kCPU));
    self_cpu.lerp_(end.cpu(), weight);
    return self;
  }

  auto end_b = end.expand(self.sizes()).contiguous();
  auto self_b = self.contiguous();

  uint32_t num_elements = self_b.numel();
  uint32_t groups_x = (num_elements + 255) / 256;

  std::vector<const uint8_t*> ptrs = {
      reinterpret_cast<const uint8_t*>(self_b.data_ptr()),
      reinterpret_cast<const uint8_t*>(end_b.data_ptr()),
      reinterpret_cast<const uint8_t*>(self.data_ptr())};

  LerpPushConstants pc = {num_elements, weight.toFloat()};

  int32_t result = vkc_dispatch(
      reinterpret_cast<void*>(it->second),
      ptrs.data(), ptrs.size(),
      groups_x, 1, 1,
      reinterpret_cast<const uint8_t*>(&pc), sizeof(pc));

  TORCH_CHECK(result == 0, "lerp_vulkan_scalar_ dispatch failed");
  return self;
}

at::Tensor lerp_vulkan_tensor(const at::Tensor& self, const at::Tensor& end, const at::Tensor& weight) {
  auto it = find_shader_for_dtype("lerp_tensor", self.scalar_type());
  if (it == g_shader_handles.end() || !has_vulkan_buffer(self) || !has_vulkan_buffer(end) || !has_vulkan_buffer(weight)) {
    vkc_flush();
    return at::lerp(self.cpu(), end.cpu(), weight.cpu()).to(self.options());
  }

  auto [self_b, end_b] = needs_broadcast(self, end) ? broadcast_operands(self, end) : std::make_pair(self.contiguous(), end.contiguous());
  auto [final_self, weight_b] = needs_broadcast(self_b, weight) ? broadcast_operands(self_b, weight) : std::make_pair(self_b.contiguous(), weight.contiguous());

  auto out = at::empty_like(final_self);
  uint32_t num_elements = final_self.numel();
  uint32_t groups_x = (num_elements + 255) / 256;

  std::vector<const uint8_t*> ptrs = {
      reinterpret_cast<const uint8_t*>(final_self.data_ptr()),
      reinterpret_cast<const uint8_t*>(end_b.expand(final_self.sizes()).contiguous().data_ptr()),
      reinterpret_cast<const uint8_t*>(weight_b.data_ptr()),
      reinterpret_cast<const uint8_t*>(out.data_ptr())};

  LerpTensorPushConstants pc = {num_elements};

  int32_t result = vkc_dispatch(
      reinterpret_cast<void*>(it->second),
      ptrs.data(), ptrs.size(),
      groups_x, 1, 1,
      reinterpret_cast<const uint8_t*>(&pc), sizeof(pc));

  TORCH_CHECK(result == 0, "lerp_vulkan_tensor dispatch failed");
  return out;
}

at::Tensor& lerp_vulkan_tensor_(at::Tensor& self, const at::Tensor& end, const at::Tensor& weight) {
  auto it = find_shader_for_dtype("lerp_tensor", self.scalar_type());
  if (it == g_shader_handles.end() || !has_vulkan_buffer(self) || !has_vulkan_buffer(end) || !has_vulkan_buffer(weight)) {
    vkc_flush();
    auto self_cpu = at::from_blob(self.data_ptr(), self.sizes(), self.strides(), at::TensorOptions().dtype(self.scalar_type()).device(c10::kCPU));
    self_cpu.lerp_(end.cpu(), weight.cpu());
    return self;
  }

  auto end_b = end.expand(self.sizes()).contiguous();
  auto weight_b = weight.expand(self.sizes()).contiguous();
  auto self_b = self.contiguous();

  uint32_t num_elements = self_b.numel();
  uint32_t groups_x = (num_elements + 255) / 256;

  std::vector<const uint8_t*> ptrs = {
      reinterpret_cast<const uint8_t*>(self_b.data_ptr()),
      reinterpret_cast<const uint8_t*>(end_b.data_ptr()),
      reinterpret_cast<const uint8_t*>(weight_b.data_ptr()),
      reinterpret_cast<const uint8_t*>(self.data_ptr())};

  LerpTensorPushConstants pc = {num_elements};

  int32_t result = vkc_dispatch(
      reinterpret_cast<void*>(it->second),
      ptrs.data(), ptrs.size(),
      groups_x, 1, 1,
      reinterpret_cast<const uint8_t*>(&pc), sizeof(pc));

  TORCH_CHECK(result == 0, "lerp_vulkan_tensor_ dispatch failed");
  return self;
}

#pragma pack(push, 1)
struct ReductionPushConstants {
    uint32_t num_elements;
};
struct DimReductionPushConstants {
    uint32_t outer_size;
    uint32_t reduce_size;
    uint32_t inner_size;
};
#pragma pack(pop)

at::Tensor vulkan_reduction(const at::Tensor& self, const char* op_name, std::optional<c10::ScalarType> dtype) {
  auto shader_it = find_shader_for_dtype("sum", self.scalar_type());
  if (shader_it == g_shader_handles.end() || !has_vulkan_buffer(self) || !self.is_contiguous()) {
    // CPU fallback: copy data to CPU, compute, copy result back.
    vkc_flush();
    auto self_cpu = at::empty(self.sizes(), self.options().device(c10::kCPU));
    std::memcpy(self_cpu.data_ptr(), self.data_ptr(), self.nbytes());
    auto r = std::strcmp(op_name, "mean") == 0 ? at::mean(self_cpu, dtype) : at::sum(self_cpu, dtype);
    auto out = at::empty(r.sizes(), self.options().dtype(r.scalar_type()));
    std::memcpy(out.data_ptr(), r.data_ptr(), r.nbytes());
    return out;
  }

  uint32_t num_elements = self.numel();
  if (num_elements == 0) {
      return at::zeros({}, self.options().dtype(dtype.value_or(self.scalar_type())));
  }

  auto current_input = self;
  uint32_t current_num = num_elements;
  bool is_mean = std::strcmp(op_name, "mean") == 0;

  // Multi-pass reduction on GPU
  while (current_num > 1) {
      // Each workgroup (256 threads) produces one partial sum.
      // Use enough workgroups to cover all elements, but cap at a reasonable
      // number to avoid excessive partial sums.
      uint32_t groups_x = std::max(1u, std::min((current_num + 255) / 256, 256u));
      std::vector<int64_t> tmp_shape = {static_cast<int64_t>(groups_x)};
      auto out = at::empty(tmp_shape, self.options());
      
      std::vector<const uint8_t*> ptrs = {
          reinterpret_cast<const uint8_t*>(current_input.data_ptr()),
          reinterpret_cast<const uint8_t*>(out.data_ptr())};

      ReductionPushConstants pc = {current_num};

      auto dispatch_it = find_shader_for_dtype("sum", self.scalar_type());

      int32_t result = vkc_dispatch(
          reinterpret_cast<void*>(dispatch_it->second),
          ptrs.data(), ptrs.size(),
          groups_x, 1, 1,
          reinterpret_cast<const uint8_t*>(&pc), sizeof(pc));

      TORCH_CHECK(result == 0, std::string("sum") + "_vulkan dispatch failed in multi-pass");
      current_input = out;
      current_num = groups_x;
  }

  // At this point current_input is a 1-element tensor containing the sum.
  if (is_mean && num_elements > 0) {
      // Divide by num_elements using mul.Scalar (since div.Scalar is not native yet)
      float scale = 1.0f / static_cast<float>(num_elements);
      current_input = current_input.mul(scale);
  }

  auto actual_dtype = dtype.value_or(self.scalar_type());
  return current_input.view({}).to(actual_dtype);
  }

at::Tensor vulkan_dim_reduction(const at::Tensor& self, at::OptionalIntArrayRef dim, bool keepdim, std::optional<c10::ScalarType> dtype, const char* op_name) {
  if (!dim.has_value() || dim.value().size() == 0) {
     return vulkan_reduction(self, std::strcmp(op_name, "mean_dim") == 0 ? "mean" : "sum", dtype);
  }

  // If multi-dim reduction, use CPU fallback since our GPU shader only handles 1D reduction.
  if (dim.value().size() > 1) {
    vkc_flush();
    auto cpu_opts = at::TensorOptions().dtype(self.scalar_type()).device(c10::kCPU);
    auto self_cpu = at::from_blob(const_cast<void*>(self.data_ptr()), self.sizes(), self.strides(), cpu_opts);
    auto r = std::strcmp(op_name, "mean_dim") == 0 ? at::mean(self_cpu, dim.value(), keepdim, dtype) : at::sum(self_cpu, dim.value(), keepdim, dtype);
    auto out = at::empty(r.sizes(), self.options().dtype(r.scalar_type()));
    std::memcpy(out.data_ptr(), r.data_ptr(), r.nbytes());
    return out;
  }

  auto it = find_shader_for_dtype(op_name, self.scalar_type());
  if (it == g_shader_handles.end() || !has_vulkan_buffer(self) || !self.is_contiguous()) {
    vkc_flush();
    auto cpu_opts = at::TensorOptions().dtype(self.scalar_type()).device(c10::kCPU);
    auto self_cpu = at::from_blob(const_cast<void*>(self.data_ptr()), self.sizes(), self.strides(), cpu_opts);
    auto r = std::strcmp(op_name, "mean_dim") == 0 ? at::mean(self_cpu, dim.value(), keepdim, dtype) : at::sum(self_cpu, dim.value(), keepdim, dtype);
    auto out = at::empty(r.sizes(), self.options().dtype(r.scalar_type()));
    std::memcpy(out.data_ptr(), r.data_ptr(), r.nbytes());
    return out;
  }

  int64_t d = dim.value()[0];
  if (d < 0) d += self.dim();
  
  uint32_t outer_size = 1;
  for (int i = 0; i < d; i++) outer_size *= self.size(i);
  uint32_t reduce_size = self.size(d);
  uint32_t inner_size = 1;
  for (int i = d + 1; i < self.dim(); i++) inner_size *= self.size(i);
  
  uint32_t total_outputs = outer_size * inner_size;
  uint32_t groups_x = (total_outputs + 255) / 256;

  std::vector<int64_t> out_sizes;
  for (int i = 0; i < self.dim(); i++) {
      if (i == d) {
          if (keepdim) out_sizes.push_back(1);
      } else {
          out_sizes.push_back(self.size(i));
      }
  }

  auto actual_dtype = dtype.value_or(self.scalar_type());
  auto out = at::empty(out_sizes, self.options().dtype(actual_dtype));

  std::vector<const uint8_t*> ptrs = {
      reinterpret_cast<const uint8_t*>(self.data_ptr()),
      reinterpret_cast<const uint8_t*>(out.data_ptr())};

  DimReductionPushConstants pc = {outer_size, reduce_size, inner_size};

  int32_t result = vkc_dispatch(
      reinterpret_cast<void*>(it->second),
      ptrs.data(), ptrs.size(),
      groups_x, 1, 1,
      reinterpret_cast<const uint8_t*>(&pc), sizeof(pc));

  TORCH_CHECK(result == 0, std::string(op_name) + "_vulkan dispatch failed");
  return out;
}

void vulkan_cpu_fallback(const c10::OperatorHandle& op, torch::jit::Stack* stack) {
  fprintf(stderr, "CPU FALLBACK: %s.%s\\n", op.operator_name().name.c_str(), op.operator_name().overload_name.c_str());
  vkc_flush();
  at::native::cpu_fallback(op, stack);
}

at::Tensor rms_norm_vulkan(
    const at::Tensor& input,
    c10::IntArrayRef normalized_shape,
    const std::optional<at::Tensor>& weight_opt,
    std::optional<double> eps) {
  return std::get<0>(native_rmsnorm_vulkan(input, normalized_shape, weight_opt, eps.value_or(1e-5)));
}

c10::Scalar local_scalar_dense_vulkan(const at::Tensor& self) {
  vkc_flush();
  // Host-mapped memory: just read the scalar directly.
  switch (self.scalar_type()) {
    case c10::ScalarType::Float:
      return c10::Scalar(*static_cast<float*>(self.data_ptr()));
    case c10::ScalarType::Half: {
      auto val = *static_cast<at::Half*>(self.data_ptr());
      return c10::Scalar(static_cast<float>(val));
    }
    case c10::ScalarType::Long:
      return c10::Scalar(*static_cast<int64_t*>(self.data_ptr()));
    case c10::ScalarType::Int:
      return c10::Scalar(*static_cast<int32_t*>(self.data_ptr()));
    case c10::ScalarType::Bool:
      return c10::Scalar(*static_cast<bool*>(self.data_ptr()));
    default:
      // Fallback: copy to CPU
      return self.cpu().item();
  }
}

// Autograd for SDPA: enables backward through F.scaled_dot_product_attention
// on PrivateUse1 tensors without needing the custom vulkan_sdpa wrapper.
at::Tensor sdpa_autograd_vulkan(
    const at::Tensor& query, const at::Tensor& key, const at::Tensor& value,
    const std::optional<at::Tensor>& attn_mask, double dropout_p,
    bool is_causal, std::optional<double> scale, bool enable_gqa) {

  // For complex cases, fall through to default (CPU fallback).
  if (attn_mask.has_value() || dropout_p > 0.0 || is_causal || enable_gqa) {
    auto result = sdpa_vulkan(query, key, value, attn_mask, dropout_p, is_causal, scale, enable_gqa);
    return result;
  }

  // Use our decomposed SDPA which supports autograd natively through
  // PyTorch's built-in autograd for matmul, softmax, etc.
  float s = scale.has_value()
      ? static_cast<float>(scale.value())
      : (1.0f / std::sqrt(static_cast<float>(query.size(-1))));

  auto scores = at::matmul(query, key.transpose(-2, -1)) * s;
  scores = at::softmax(scores, -1);
  return at::matmul(scores, value);
}

TORCH_LIBRARY_IMPL(aten, AutogradPrivateUse1, m) {
  m.impl("scaled_dot_product_attention", &sdpa_autograd_vulkan);
  m.impl("_softmax_backward_data", &softmax_backward_data_vulkan);
  m.impl("_softmax_backward_data.out", &softmax_backward_data_out_vulkan);
  m.impl("sub.out", &sub_out_vulkan);
  m.impl("native_layer_norm_backward", &native_layer_norm_backward_vulkan);
  m.impl("_fused_rms_norm_backward", &fused_rms_norm_backward_vulkan);

  m.impl("rms_norm", torch::CppFunction::makeFallthrough());
  m.impl("native_layer_norm", torch::CppFunction::makeFallthrough());
}

TORCH_LIBRARY_IMPL(_, PrivateUse1, m) {
  m.fallback(torch::CppFunction::makeFromBoxedFunction<&vulkan_cpu_fallback>());
}

TORCH_LIBRARY_IMPL(aten, PrivateUse1, m) {
  m.impl("empty.memory_format", &empty_vulkan);
  m.impl("empty_strided", &empty_strided_vulkan);
  m.impl("copy_", &copy_vulkan_);
  m.impl("fill_.Scalar", &fill_vulkan_);
  m.impl("zero_", &zero_vulkan_);
  m.impl("normal_", &normal_vulkan_);
  m.impl("uniform_", &uniform_vulkan_);
  m.impl("resize_", &resize_vulkan_);
  m.impl("_copy_from_and_resize", &_copy_from_and_resize_vulkan);
  m.impl("embedding", &embedding_vulkan);
  m.impl("view", TORCH_FN(view_vulkan));
  m.impl("_reshape_alias", &_reshape_alias_vulkan);
  m.impl("expand", &expand_vulkan);
  m.impl("as_strided", &as_strided_vulkan);
  m.impl("detach", &detach_vulkan);
  m.impl("_to_copy", &_to_copy_vulkan);
  m.impl("add.Tensor", &add_vulkan);
  m.impl("add_.Tensor", &add__vulkan);
  m.impl("add.out", &add_out_vulkan);
  m.impl("mul.Tensor", &mul_vulkan);
  m.impl("sub.Tensor", &sub_vulkan);
  m.impl("relu", &relu_vulkan);
  m.impl("neg", &neg_vulkan);
  m.impl("sigmoid", &sigmoid_vulkan);
  m.impl("tanh", &tanh_vulkan);
  m.impl("exp", &exp_vulkan);
  m.impl("log", &log_vulkan);
  m.impl("silu", &silu_vulkan);
  m.impl("sqrt", &sqrt_vulkan);
  m.impl("rsqrt", &rsqrt_vulkan);
  m.impl("abs", &abs_vulkan);
  m.impl("div.Tensor", &div_vulkan);
  m.impl("threshold_backward", &threshold_backward_vulkan);
  m.impl("_local_scalar_dense", &local_scalar_dense_vulkan);
  m.impl("pow.Tensor_Scalar", &pow_tensor_scalar_vulkan);
  m.impl("cat", &cat_vulkan);
  m.impl("addcdiv", &addcdiv_vulkan);
  m.impl("addcdiv_", &addcdiv_vulkan_);
  m.impl("addcmul", &addcmul_vulkan);
  m.impl("addcmul_", &addcmul_vulkan_);
  m.impl("lerp.Scalar", &lerp_vulkan_scalar);
  m.impl("lerp_.Scalar", &lerp_vulkan_scalar_);
  m.impl("lerp.Tensor", &lerp_vulkan_tensor);
  m.impl("lerp_.Tensor", &lerp_vulkan_tensor_);
  // In-place scalar ops: used heavily by Adam optimizer.
  // Since memory is host-mapped, we flush + operate directly on CPU.
  m.impl("add_.Scalar", [](at::Tensor& self, const at::Scalar& other, const at::Scalar& alpha) -> at::Tensor& {
    vkc_flush();
    float val = other.toFloat() * alpha.toFloat();
    float* ptr = static_cast<float*>(self.data_ptr());
    for (int64_t i = 0; i < self.numel(); i++) ptr[i] += val;
    return self;
  });
  m.impl("mul_.Scalar", [](at::Tensor& self, const at::Scalar& other) -> at::Tensor& {
    vkc_flush();
    float val = other.toFloat();
    float* ptr = static_cast<float*>(self.data_ptr());
    for (int64_t i = 0; i < self.numel(); i++) ptr[i] *= val;
    return self;
  });
  m.impl("div_.Scalar", [](at::Tensor& self, const at::Scalar& other) -> at::Tensor& {
    vkc_flush();
    float val = other.toFloat();
    float* ptr = static_cast<float*>(self.data_ptr());
    for (int64_t i = 0; i < self.numel(); i++) ptr[i] /= val;
    return self;
  });
  m.impl("add.Scalar", [](const at::Tensor& self, const at::Scalar& other, const at::Scalar& alpha) -> at::Tensor {
    vkc_flush();
    auto out = self.clone();
    float val = other.toFloat() * alpha.toFloat();
    float* ptr = static_cast<float*>(out.data_ptr());
    for (int64_t i = 0; i < out.numel(); i++) ptr[i] += val;
    return out;
  });
  m.impl("mul.Scalar", [](const at::Tensor& self, const at::Scalar& other) -> at::Tensor {
    vkc_flush();
    auto out = self.clone();
    float val = other.toFloat();
    float* ptr = static_cast<float*>(out.data_ptr());
    for (int64_t i = 0; i < out.numel(); i++) ptr[i] *= val;
    return out;
  });
  m.impl("sum.dim_IntList", [](const at::Tensor& self,
      at::OptionalIntArrayRef dim, bool keepdim,
      std::optional<c10::ScalarType> dtype) -> at::Tensor {
      return vulkan_dim_reduction(self, dim, keepdim, dtype, "sum_dim");
  });
  m.impl("sum", [](const at::Tensor& self, std::optional<c10::ScalarType> dtype) -> at::Tensor {
      return vulkan_reduction(self, "sum", dtype);
  });
  m.impl("div.Scalar", [](const at::Tensor& self, const at::Scalar& other) -> at::Tensor {
    vkc_flush();
    auto out = self.clone();
    float val = other.toFloat();
    float* ptr = static_cast<float*>(out.data_ptr());
    for (int64_t i = 0; i < out.numel(); i++) ptr[i] /= val;
    return out;
  });
  // argmax: used in generation for greedy token selection
  m.impl("argmax", [](const at::Tensor& self, std::optional<int64_t> dim, bool keepdim) -> at::Tensor {
    vkc_flush();
    auto self_cpu = at::empty(self.sizes(), self.options().device(c10::kCPU));
    std::memcpy(self_cpu.data_ptr(), self.data_ptr(), self.nbytes());
    auto r = at::argmax(self_cpu, dim, keepdim);
    auto out = at::empty(r.sizes(), self.options().dtype(r.scalar_type()));
    std::memcpy(out.data_ptr(), r.data_ptr(), r.nbytes());
    return out;
  });
  // Reductions natively (GPU dispatch).
  m.impl("mean", [](const at::Tensor& self, std::optional<c10::ScalarType> dtype) -> at::Tensor {
      return vulkan_reduction(self, "mean", dtype);
  });
  m.impl("mean.dim", [](const at::Tensor& self, at::OptionalIntArrayRef dim,
      bool keepdim, std::optional<c10::ScalarType> dtype) -> at::Tensor {
      return vulkan_dim_reduction(self, dim, keepdim, dtype, "mean_dim");
  });
  // MSE loss: decompose into native ops to avoid fused CPU fallback.
  // NOTE: cross-entropy (_log_softmax, nll_loss) falls back to CPU via
  // the generic fallback. Native registration attempted but backward
  // path has device tracking issues with 0-dim tensors. TODO: fix.
  m.impl("mse_loss", [](const at::Tensor& self, const at::Tensor& target, int64_t reduction) -> at::Tensor {
    auto diff = self - target;
    auto sq = diff * diff;
    if (reduction == 0) return sq;
    if (reduction == 1) return sq.mean();
    return sq.sum();
  });
  m.impl("mse_loss_backward", [](const at::Tensor& grad_output,
      const at::Tensor& self, const at::Tensor& target, int64_t reduction) -> at::Tensor {
    auto diff = self - target;
    auto n = static_cast<float>(self.numel());
    if (reduction == 1) {
      return diff * (2.0f / n) * grad_output;
    } else if (reduction == 2) {
      return diff * 2.0f * grad_output;
    }
    return diff * 2.0f * grad_output;
  });
  m.impl("gelu", &gelu_vulkan);
  // native_layer_norm and native_rms_norm: re-enabled in PrivateUse1
  // since we registered the backward kernels at AutogradPrivateUse1.
  // native_rms_norm and native_layer_norm DISABLED at PrivateUse1.
  // Re-enabling breaks training (autograd can't trace backward) and
  // We are re-enabling these as we have added their backward paths.
  m.impl("native_layer_norm", &native_layer_norm_vulkan);
  m.impl("_fused_rms_norm", &fused_rms_norm_vulkan);
  m.impl("mm", &mm_vulkan);
  m.impl("bmm", &bmm_vulkan);
  m.impl("addmm", &addmm_vulkan);
  m.impl("_softmax", &softmax_vulkan);
  m.impl("scaled_dot_product_attention", &sdpa_vulkan);
  // Native decomposed encoder: 51ms (was 200ms before async copy, now 51ms).
  // CPU fallback: 18ms. Still faster because one bulk copy vs many dispatches.
  // TODO: Fuse the decomposition into a single GPU kernel for parity.
  // m.impl("_transformer_encoder_layer_fwd", &transformer_encoder_layer_fwd_vulkan);
}

}  // anonymous namespace

// ---------------------------------------------------------------------------
// Python module
// ---------------------------------------------------------------------------

PYBIND11_MODULE(_C, m) {
  m.def("init", []() -> bool {
    return vkc_init() == 0;
  });
  m.def("is_available", []() -> bool {
    return vkc_is_available() == 1;
  });
  m.def("device_count", []() -> int64_t {
    return vkc_is_available() == 1 ? 1 : 0;
  });
  m.def("device_name", []() -> std::string {
    char buf[256];
    int n = vkc_device_name(buf, sizeof(buf));
    return n > 0 ? std::string(buf, n) : "N/A";
  });
  m.def("flush", []() -> int64_t {
    return vkc_flush() == 0 ? 1 : 0;
  });
  m.def("test_hello", []() -> int64_t {
    std::cout << "HELLO FROM C++!" << std::endl;
    return 42;
  });
  // --- Shader / dispatch API for the Inductor backend ---

  m.def("register_shader_handle", [](const std::string& op_name, int64_t handle) {
    g_shader_handles[op_name] = handle;
  });

  // Load SPIR-V bytecode, returns an opaque pipeline handle (int).
  m.def("load_shader", [](py::bytes spirv) -> int64_t {
    std::string data = spirv;
    void* handle = vkc_load_shader(
        reinterpret_cast<const uint8_t*>(data.data()), data.size());
    return reinterpret_cast<int64_t>(handle);
  });
  // Dispatch a compute shader over tensors.
  //   pipeline_handle: int64 from load_shader
  //   tensors: list of PrivateUse1 tensors (their data_ptrs are passed as buffers)
  //   group_count: (x, y, z) workgroup counts
  //   push_constants: bytes object for push constant data
  m.def("dispatch", [](
      int64_t pipeline_handle,
      std::vector<at::Tensor> tensors,
      std::tuple<uint32_t, uint32_t, uint32_t> group_count,
      py::bytes push_constants) -> bool {
    void* handle = reinterpret_cast<void*>(pipeline_handle);

    std::vector<const uint8_t*> ptrs;
    ptrs.reserve(tensors.size());
    for (auto& t : tensors) {
      ptrs.push_back(reinterpret_cast<const uint8_t*>(t.data_ptr()));
    }

    std::string pc_data = push_constants;
    auto [gx, gy, gz] = group_count;

    int32_t result = vkc_dispatch(
        handle,
        ptrs.data(),
        ptrs.size(),
        gx, gy, gz,
        reinterpret_cast<const uint8_t*>(pc_data.data()),
        pc_data.size());

    return result == 0;
  });
}
