#version 450
#extension GL_EXT_shader_16bit_storage : require
layout(local_size_x = 256) in;
layout(set = 0, binding = 0) readonly buffer InputA { float16_t a[]; };
layout(set = 0, binding = 1) readonly buffer InputB { float16_t b[]; };
layout(set = 0, binding = 2) readonly buffer InputC { float16_t c[]; };
layout(set = 0, binding = 3) writeonly buffer OutputD { float16_t d[]; };

layout(push_constant) uniform PushConstants {
    uint num_elements;
    float value;
} pc;

void main() {
    uint idx = gl_GlobalInvocationID.x;
    if (idx < pc.num_elements) {
        d[idx] = float16_t(float(a[idx]) + pc.value * (float(b[idx]) * float(c[idx])));
    }
}