#version 450

layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;

layout(set = 0, binding = 0) readonly buffer InputA {
    float A[];
};

layout(set = 0, binding = 1) readonly buffer InputB {
    float B[];
};

layout(set = 0, binding = 2) writeonly buffer OutputC {
    float C[];
};

layout(push_constant) uniform PushConstants {
    uint M;
    uint N;
    uint K;
} pc;

void main() {
    uint row = gl_GlobalInvocationID.y; // M
    uint col = gl_GlobalInvocationID.x; // N

    if (row < pc.M && col < pc.N) {
        float sum = 0.0;
        for (uint i = 0; i < pc.K; ++i) {
            sum += A[row * pc.K + i] * B[i * pc.N + col];
        }
        C[row * pc.N + col] = sum;
    }
}
