#version 450
#extension GL_EXT_shader_explicit_arithmetic_types_float16 : require

layout(local_size_x = 256) in;

layout(set = 0, binding = 0) buffer Data { float16_t data[]; };

layout(push_constant) uniform PushConstants {
    uint num_elements;
    float value;
} pc;

void main() {
    uint idx = gl_GlobalInvocationID.x;
    if (idx < pc.num_elements) {
        data[idx] = float16_t(float(data[idx]) * pc.value);
    }
}
