#version 450

layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

layout(set = 0, binding = 0) readonly buffer InputA {
    float A[];
};

layout(set = 0, binding = 1) writeonly buffer OutputC {
    float C[];
};

layout(push_constant) uniform PushConstants {
    uint num_elements;
} pc;

void main() {
    uint idx = gl_GlobalInvocationID.x;
    if (idx < pc.num_elements) {
        C[idx] = 1.0;
    }
}
